import type { Article } from "./articles";

export const POOLED_ARTICLES: Article[] = [
  {
    slug: "pool-001",
    title: "这个乳制品与痘痘问题，太多人忽略了",
    kicker: "Pharmacist explains",
    category: "Supplement",
    date: "07 May 2025",
    readTime: "3 min",
    excerpt: "如果你痘痘一直反反复复，也许该试试减少乳制品——很多人不知道这两者的关联。",
    cover: "/editorial/story-brightening.png",
    accent: "#a65a2f",
    body: [
      { text: "如果你痘痘一直反反复复，也许该试试减少乳制品——很多人不知道这两者的关联。" },
      { text: "有没有想过为什么？" },
      { text: "酸奶和发酵乳制品的影响可能较小——发酵过程分解了部分 IGF-1。" },
      { text: "牛奶中的 IGF-1（类胰岛素生长因子）可以刺激皮脂分泌——痘痘形成的关键环节。" },
      { text: "脱脂牛奶的影响可能比全脂更大——加工过程改变了蛋白质结构，IGF-1 含量反而更高。" },
      { heading: "🥛 重点整理", text: "✅ 可以试试减少或排除乳制品 2–4 周观察变化\n✅ 酸奶是相对安全的替代——发酵过程改变了牛奶蛋白\n❌ 不是说所有人都要戒牛奶——观察自己的身体反应\n❌ 不要盲目跟风——每个人的情况不同" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-002",
    title: "关于姜黄，药师想说的六件事",
    kicker: "Kris notes",
    category: "Ingredient",
    date: "05 Dec 2025",
    readTime: "3 min",
    excerpt: "姜黄不只是咖喱里的香料——它是一种强大的抗炎成分。但有一个问题：单独服用吸收率很低。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "姜黄不只是咖喱里的香料——它是一种强大的抗炎成分。但有一个问题：单独服用吸收率很低。" },
      { text: "怎么说呢？" },
      { text: "Curcumin（姜黄素）需要搭配黑胡椒中的胡椒碱才能显著提高吸收——可以提高 2000%。" },
      { text: "Osteoliv 中就含有姜黄素——搭配其他成分协同作用。" },
      { text: "研究表明姜黄对关节炎、消化问题和全身性炎症都有潜在帮助。" },
      { heading: "🟡 重点整理", text: "✅ 搭配黑胡椒吸收率提高 2000%\n✅ 抗炎 + 抗氧化双重功效\n✅ 对关节和消化都有帮助\n❌ 不要单独服用姜黄粉——吸收率很低\n❌ 姜黄会让衣服和台面染色——小心使用" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoGard——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-003",
    title: "色素沉着：你真的补对了吗？",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "05 Apr 2025",
    readTime: "3 min",
    excerpt: "防晒是所有色素治疗的基础——没有防晒，其他治疗效果都打折扣。但很多人忽略这一点。",
    cover: "/editorial/hero.jpg",
    accent: "#a62f4f",
    body: [
      { text: "防晒是所有色素治疗的基础——没有防晒，其他治疗效果都打折扣。但很多人忽略这一点。" },
      { text: "简单来说：" },
      { text: "外用成分：维生素 C（抗氧化+美白）、烟酰胺（抑制转运）、壬二酸（抑制酪氨酸酶）。" },
      { text: "传明酸适合黄褐斑——通过抑制纤溶酶原激活来减少色素。" },
      { text: "色素淡化需要时间——至少 3–6 个月才能看到明显变化。不要指望一周见效。" },
      { heading: "✨ 重点整理", text: "✅ 防晒是所有色素治疗的基础——不防晒其他都白做\n✅ 维 C + 烟酰胺 + 壬二酸是经典组合\n✅ 给皮肤足够的时间——3–6 个月\n❌ 不要指望一周见效——色素淡化需要耐心\n❌ 不要忽略防晒——紫外线会加重色素沉着" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-004",
    title: "搞懂烟酰胺，别再交智商税",
    kicker: "Kris notes",
    category: "Clinical",
    date: "24 Feb 2025",
    readTime: "3 min",
    excerpt: "烟酰胺（Niacinamide）是维生素 B3 的衍生物，一个超全能的护肤成分——但很多人用错了浓度。",
    cover: "/products/fortress-plus-1.png",
    accent: "#2fa66b",
    body: [
      { text: "烟酰胺（Niacinamide）是维生素 B3 的衍生物，一个超全能的护肤成分——但很多人用错了浓度。" },
      { text: "先来看看研究怎么说。" },
      { text: "烟酰胺可以帮助控制皮脂分泌、缩小毛孔外观、强化皮肤屏障、改善色素沉着——几乎什么都能做。" },
      { text: "和维生素 C 可以一起使用——现代研究已经推翻了早期「不能同时用」的说法。" },
      { text: "建议浓度在 2–5% 之间——10% 反而可能引起刺激和泛红。不是浓度越高越好。" },
      { heading: "✨ 重点整理", text: "✅ 适合几乎所有肤质，包括敏感肌\n✅ 2–5% 浓度就可以看到效果\n✅ 早晚都可以使用——温和不刺激\n❌ 不是浓度越高越好——10% 可能反而刺激\n❌ 不要和高浓度酸类同时叠加——可能增加刺激风险" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "你有试过烟酰胺相关的产品吗？我想听听你的分享。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-005",
    title: "搞懂玻尿酸，别再交智商税",
    kicker: "Clinical notes",
    category: "Editorial",
    date: "09 Feb 2025",
    readTime: "3 min",
    excerpt: "玻尿酸可以吸收自身重量 1000 倍的水分——但用错方式反而会吸走皮肤的水分。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#6a5a8a",
    body: [
      { text: "玻尿酸可以吸收自身重量 1000 倍的水分——但用错方式反而会吸走皮肤的水分。" },
      { text: "也就是说——" },
      { text: "皮肤中的玻尿酸可以帮助维持含水量，让皮肤看起来饱满有弹性。但随着年龄增长，合成能力会下降。" },
      { text: "口服玻尿酸研究显示对皮肤水分和关节健康都有帮助——不只是外用有效。" },
      { text: "在干燥环境下单独使用玻尿酸可能反而吸走皮肤水分——需要搭配封闭剂。" },
      { heading: "💧 重点整理", text: "✅ 外用要搭配封闭剂（如面霜）锁住水分\n✅ 口服玻尿酸研究支持对皮肤和关节有益\n✅ 分子量越小渗透越深——但不一定越好\n❌ 干燥环境下单独用玻尿酸可能反而吸走水分\n❌ 不是所有玻尿酸产品浓度都够" },
      { heading: "药师小贴士 💊", text: "💊 每个人的体质不同，适合别人的不一定适合你。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-006",
    title: "先别急着买益生菌",
    kicker: "Pharmacist explains",
    category: "Editorial",
    date: "11 Apr 2025",
    readTime: "3 min",
    excerpt: "很多人以为益生菌只是「帮助消化」。其实它的影响力远超你的想象——从免疫到情绪到皮肤。",
    cover: "/editorial/story-brightening.png",
    accent: "#b07c2f",
    body: [
      { text: "很多人以为益生菌只是「帮助消化」。其实它的影响力远超你的想象——从免疫到情绪到皮肤。" },
      { text: "也就是说——" },
      { text: "肠道菌群的数量超过人体细胞的总数——它们不是「寄生虫」，而是共生伙伴。" },
      { text: "不同菌株有不同的功能——Lactobacillus 和 Bifidobacterium 是研究最充分的两大类。" },
      { text: "Fortress 里的益生菌可以杀死超过 80% 痘痘细菌——外用益生菌也开始受到关注。" },
      { heading: "🦠 重点整理", text: "✅ 选择含有研究充分菌株的产品\n✅ 搭配膳食纤维效果更好\n❌ 不是所有益生菌都一样——菌株特异性很重要\n❌ 不要和热饮一起服用——高温会杀死活性菌" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-007",
    title: "护肤顺序：药师的实用小课堂",
    kicker: "Kris notes",
    category: "Ingredient",
    date: "07 Feb 2025",
    readTime: "3 min",
    excerpt: "护肤顺序其实很简单——但很多人搞复杂了。你不需要十几步才能拥有好皮肤。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#a65a2f",
    body: [
      { text: "护肤顺序其实很简单——但很多人搞复杂了。你不需要十几步才能拥有好皮肤。" },
      { text: "也就是说——" },
      { text: "多余的产品反而可能增加刺激风险——不是越多越好。" },
      { text: "质地从薄到厚、从水基到油基——这是为了让每一步都能被皮肤吸收。" },
      { text: "正确顺序：清洁 → 精华 → 面霜 → 防晒（白天）。核心只需要这 4 步。" },
      { heading: "📋 重点整理", text: "✅ 清洁 → 精华 → 面霜 → 防晒——4 步足够\n✅ 新产品一个一个加入——不要同时引入太多\n✅ 晚上可以省略防晒，加入 A 醇或酸类\n❌ 不要一次叠加太多活性成分——会打架\n❌ 不要过度清洁——会破坏屏障" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "你有试过护肤顺序相关的产品吗？我想听听你的分享。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-008",
    title: "儿童护肤的真相，和你想的不一样",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "05 Apr 2025",
    readTime: "3 min",
    excerpt: "孩子的皮肤比成人薄——护肤品的选择原则就是：温和、简单。不需要大人的那些「进阶」产品。",
    cover: "/editorial/hero.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "孩子的皮肤比成人薄——护肤品的选择原则就是：温和、简单。不需要大人的那些「进阶」产品。" },
      { text: "也就是说——" },
      { text: "物理防晒（氧化锌）对儿童来说更安全——不会被皮肤吸收。" },
      { text: "日常只需要：温和清洁 + 基础保湿 + 防晒（6 个月以上）。" },
      { text: "儿童皮肤屏障功能还不完善——过度清洁反而会伤害皮肤。" },
      { heading: "👶 重点整理", text: "✅ 温和清洁 + 基础保湿 + 防晒\n✅ 物理防晒对儿童更安全\n✅ 选择专门为儿童设计的产品\n❌ 不要用成人产品给孩子——浓度和成分不适合\n❌ 不要给孩子用美白、抗老产品——没必要" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "有问题欢迎留言区讨论！" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-009",
    title: "为什么你的视黄醇一直没效？",
    kicker: "Kris supplement notes",
    category: "Clinical",
    date: "27 Oct 2025",
    readTime: "3 min",
    excerpt: "A 醇（Retinol）是目前研究最充分的抗老成分之一。但使用不当反而会伤害皮肤——入门第一课：慢慢来。",
    cover: "/products/fortress-plus-1.png",
    accent: "#a62f4f",
    body: [
      { text: "A 醇（Retinol）是目前研究最充分的抗老成分之一。但使用不当反而会伤害皮肤——入门第一课：慢慢来。" },
      { text: "先来看看研究怎么说。" },
      { text: "A 醇可以促进胶原蛋白生成、加速细胞更新、改善细纹和肤色不均——是抗老的「黄金标准」。" },
      { text: "使用后一定要保湿，白天一定要防晒——A 醇会让皮肤对紫外线更敏感。" },
      { text: "从低浓度（0.25–0.3%）开始，每周 2–3 次，让皮肤慢慢建立耐受——通常需要 4–6 周。" },
      { heading: "🌙 重点整理", text: "✅ 从低浓度开始，每周 2–3 次\n✅ 使用后保湿 + 白天防晒是必须的\n✅ 搭配烟酰胺可以减少刺激\n❌ 不要一上来就用高浓度——会脱皮到你怀疑人生\n❌ 不要和高浓度酸类同时使用\n❌ 孕妇和哺乳期避免使用——有致畸风险" },
      { text: "A 醇和 A 酸（Tretinoin）不同——A 醇需要在皮肤中转化才能起效，所以更温和。" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-010",
    title: "先别急着买关节保健",
    kicker: "Supplement truths",
    category: "Clinical",
    date: "26 Mar 2025",
    readTime: "3 min",
    excerpt: "怎么说呢？关节问题不是老年人才有的。很多人 30 岁就开始「沙沙」了。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#2fa66b",
    body: [
      { text: "怎么说呢？关节问题不是老年人才有的。很多人 30 岁就开始「沙沙」了。" },
      { text: "但问题来了。" },
      { text: "运动前后适当补充关节营养，可以减少运动损伤的风险。" },
      { text: "关节液的成分和滑膜的功能直接影响关节灵活性——不是只有软骨需要保养。" },
      { text: "久坐、缺乏运动、体重过重都会加速关节磨损。" },
      { heading: "🦴 重点整理", text: "✅ 30 岁以后就该开始关注关节健康\n✅ 适度运动比完全不动对关节更好\n❌ 不要以为「痛就不要动」——适度活动反而有助于关节保养\n❌ 不要盲目跟风买关节保健品——看成分" },
      { heading: "药师小贴士 💊", text: "💊 每个人的体质不同，适合别人的不一定适合你。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoGard——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-011",
    title: "荷尔蒙与皮肤入门第一课，别再走弯路",
    kicker: "Clinical notes",
    category: "Editorial",
    date: "17 Jul 2025",
    readTime: "3 min",
    excerpt: "你的荷尔蒙正在影响你的皮肤——月经周期、压力、年龄都在改变你的皮肤状态。很多人不知道这一点。",
    cover: "/editorial/story-brightening.png",
    accent: "#6a5a8a",
    body: [
      { text: "你的荷尔蒙正在影响你的皮肤——月经周期、压力、年龄都在改变你的皮肤状态。很多人不知道这一点。" },
      { text: "先来看看研究怎么说。" },
      { text: "月经前黄体酮上升——皮脂分泌增加，痘痘更容易爆发。记录周期可以帮助预测。" },
      { text: "甲状腺问题也可能导致皮肤干燥、脱发、指甲变脆——如果症状持续，看医生检查。" },
      { text: "怀孕和更年期荷尔蒙变化会导致色素沉着和干燥——需要调整护肤策略。" },
      { heading: "🔬 重点整理", text: "✅ 记录月经周期和痘痘爆发的时间——找出规律\n✅ 如果怀疑荷尔蒙问题——看医生做检查\n✅ 不同荷尔蒙阶段需要不同的护肤策略\n❌ 不要自己乱吃调节荷尔蒙的保健品\n❌ 不要忽视持续的皮肤变化" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-012",
    title: "防晒的真相，和你想的不一样",
    kicker: "Kris supplement notes",
    category: "Ingredient",
    date: "23 Jan 2026",
    readTime: "3 min",
    excerpt: "很多人以为 SPF 越高越好。其实不完全是——SPF30 和 SPF50 的实际差距只有 1%。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#b07c2f",
    body: [
      { text: "很多人以为 SPF 越高越好。其实不完全是——SPF30 和 SPF50 的实际差距只有 1%。" },
      { text: "怎么说呢？" },
      { text: "真正重要的不是 SPF 数字，而是有没有擦足够量（脸部约 1/4 茶匙）和有没有每两小时补擦一次。" },
      { text: "SPF15 阻挡约 93% UVB，SPF30 约 97%，SPF50 约 98%。从 30 到 50 只多了 1% 的防护力——但价格可能贵了一倍。" },
      { text: "广谱（Broad Spectrum）标签很重要——只防 UVB 不防 UVA 的防晒霜是不够的。" },
      { heading: "☀️ 重点整理", text: "✅ SPF30 广谱防护已经足够日常使用\n✅ 出门前 15 分钟擦，每 2 小时补擦一次\n✅ 物理防晒（氧化锌）对敏感肌更安全\n❌ 不是 SPF50 就比 SPF30 强很多——实际差距只有 1%\n❌ 阴天也要防晒——UVA 穿透云层\n❌ 不要只涂脸——耳朵、脖子、手背也要照顾到" },
      { text: "UVA 可以穿透玻璃和云层——室内靠窗也会晒黑。UVA 是导致皮肤老化和色素沉着的主要元凶。" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-013",
    title: "抗氧化全攻略的真相，和你想的不一样",
    kicker: "Supplement truths",
    category: "Editorial",
    date: "21 Jan 2025",
    readTime: "3 min",
    excerpt: "抗氧化是护肤的核心——但很多人不知道从何开始。自由基是皮肤衰老的主要原因之一。",
    cover: "/editorial/hero.jpg",
    accent: "#a65a2f",
    body: [
      { text: "抗氧化是护肤的核心——但很多人不知道从何开始。自由基是皮肤衰老的主要原因之一。" },
      { text: "怎么说呢？" },
      { text: "防晒是最好的抗氧化——紫外线是最大的自由基来源。不防晒，抗氧化白做。" },
      { text: "多酚类（如绿茶萃取、白藜芦醇、虾青素）也是强大的抗氧化剂。" },
      { text: "维生素 C + 维生素 E 搭配使用效果更好——两者可以互相再生，1+1>2。" },
      { heading: "🛡️ 重点整理", text: "✅ 维 C + 维 E 搭配效果 1+1>2\n✅ 防晒是最好的抗氧化——最大的自由基来源是紫外线\n✅ 多种抗氧化剂搭配比单一更好\n❌ 不要只靠一种抗氧化剂——多种搭配更好\n❌ 不要忽略防晒——不防晒抗氧化白做" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-014",
    title: "维生素C护肤：你真的补对了吗？",
    kicker: "Kris notes",
    category: "Supplement",
    date: "04 Aug 2025",
    readTime: "3 min",
    excerpt: "维生素 C 是最经典的抗氧化成分之一——但用错了方式，效果大打折扣。",
    cover: "/products/fortress-plus-1.png",
    accent: "#2f6a7d",
    body: [
      { text: "维生素 C 是最经典的抗氧化成分之一——但用错了方式，效果大打折扣。" },
      { text: "但问题来了。" },
      { text: "和烟酰胺可以一起使用——现代研究已推翻了早期「不能同时用」的说法。" },
      { text: "产品应该是棕色或不透明包装——透明包装会让维 C 快速氧化。变黄说明已经失效。" },
      { text: "维 C + 防晒 = 更强的防晒效果——维 C 可以帮助中和紫外线产生的自由基。" },
      { text: "L-ascorbic acid 是最有效的形式——浓度 10–20% 最佳。pH 值需要在 3.5 以下才能有效渗透。" },
      { heading: "🍊 重点整理", text: "✅ 早晨使用搭配防晒效果更好\n✅ L-ascorbic acid 浓度 10–20% 最佳\n✅ 选择棕色/不透明包装的产品\n❌ 不要买透明包装的维 C 精华——容易氧化\n❌ 变黄变棕色就不要用了——已经失效" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "💬 你还知道什么关于维生素C护肤的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-015",
    title: "烟酰胺：你真的补对了吗？",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "09 Jan 2025",
    readTime: "3 min",
    excerpt: "你以为美白只能靠维 C？烟酰胺也很强——而且更温和，适合更多人。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#a62f4f",
    body: [
      { text: "你以为美白只能靠维 C？烟酰胺也很强——而且更温和，适合更多人。" },
      { text: "怎么说呢？" },
      { text: "烟酰胺的美白机制和维 C 不同——它抑制黑色素从黑色素细胞转运到角质细胞。" },
      { text: "两者搭配使用可以双重美白——一个在源头抑制，一个在运输拦截。" },
      { text: "烟酰胺还可以帮助减少毛孔外观——通过调节皮脂分泌实现。" },
      { heading: "✨ 重点整理", text: "✅ 维 C + 烟酰胺是经典美白组合\n✅ 敏感肌也能用——从低浓度开始\n❌ 不要同时使用高浓度两者——可能刺激\n❌ 不要期望立竿见影——需要持续使用 4–8 周" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-016",
    title: "关于孕妇护肤，药师想说的六件事",
    kicker: "Pharmacist explains",
    category: "Editorial",
    date: "27 Jan 2026",
    readTime: "3 min",
    excerpt: "怀孕期间有些护肤成分需要避免——你知道哪些吗？不确定的时候，先咨询产科医生。",
    cover: "/editorial/story-brightening.png",
    accent: "#2fa66b",
    body: [
      { text: "怀孕期间有些护肤成分需要避免——你知道哪些吗？不确定的时候，先咨询产科医生。" },
      { text: "先来个基础课。" },
      { text: "❌ 维 A 酸/视黄醇——口服是明确致畸的，外用虽然全身吸收量小但建议避免。" },
      { text: "怀孕期间黄褐斑可能加重——荷尔蒙变化导致色素沉着增加。物理防晒更加重要。" },
      { text: "✅ 安全成分：烟酰胺、透明质酸、神经酰胺、维生素 C、物理防晒。" },
      { heading: "🤰 重点整理", text: "✅ 烟酰胺、透明质酸、神经酰胺是安全的\n✅ 物理防晒（氧化锌）对孕妇安全\n✅ 维生素 C 精华也是安全的选择\n❌ 避免维 A 酸/视黄醇——口服明确致畸\n❌ 避免高浓度水杨酸——虽然外用风险低但建议避免" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-017",
    title: "关于成分党入门，药师想说的四件事",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "06 May 2025",
    readTime: "3 min",
    excerpt: "想看懂护肤品成分表其实不难——学会这几招就够了。不需要化学学位。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#6a5a8a",
    body: [
      { text: "想看懂护肤品成分表其实不难——学会这几招就够了。不需要化学学位。" },
      { text: "简单来说：" },
      { text: "有些成分在很低浓度下就有效（如视黄醇 0.3%、烟酰胺 2%）——不是浓度越高越好。" },
      { text: "防腐剂后面的成分浓度通常很低——如果活性成分排在防腐剂后面，含量可能不够。" },
      { text: "成分表按浓度从高到低排列——前 5 个通常占了产品的 80% 以上。" },
      { heading: "📚 重点整理", text: "✅ 前 5 个成分决定产品的主要功效\n✅ 看成分比看品牌更重要\n✅ 学会识别常见的刺激成分\n❌ 不是浓度越高越好——要看具体成分\n❌ 不要被「含有 XX」骗了——要看排在第几位" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "💬 你还知道什么关于成分党入门的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-018",
    title: "维生素B群的三个冷知识",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "22 Jan 2026",
    readTime: "3 min",
    excerpt: "维生素 B 群不是「吃了尿会变黄」这么简单——它对皮肤和头发健康都很重要。",
    cover: "/editorial/hero.jpg",
    accent: "#b07c2f",
    body: [
      { text: "维生素 B 群不是「吃了尿会变黄」这么简单——它对皮肤和头发健康都很重要。" },
      { text: "但问题来了。" },
      { text: "压力大时 B 群消耗会增加——需要额外补充。素食者也需要特别注意 B12 的摄取。" },
      { text: "B7（生物素）对头发和指甲健康特别重要——缺 B7 会导致脱发和指甲脆弱。" },
      { text: "B 群参与能量代谢、神经功能和皮肤健康——是身体的「能量转换器」。" },
      { heading: "💊 重点整理", text: "✅ 均衡饮食通常可以获取足够的 B 群\n✅ 压力大时可以考虑补充\n✅ 素食者需要特别关注 B12\n❌ 不要空腹吃高剂量 B 群——可能引起胃部不适\n❌ 尿液变黄是正常的——不代表吸收更好" },
      { heading: "药师小贴士 💊", text: "💊 每个人的体质不同，适合别人的不一定适合你。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-019",
    title: "搞懂护肤迷思，别再交智商税",
    kicker: "Pharmacist explains",
    category: "Ingredient",
    date: "16 Oct 2025",
    readTime: "3 min",
    excerpt: "护肤迷思比你想的多——今天来破解几个最常见的。很多人花大钱买产品，却被迷思误导了。",
    cover: "/products/fortress-plus-1.png",
    accent: "#a65a2f",
    body: [
      { text: "护肤迷思比你想的多——今天来破解几个最常见的。很多人花大钱买产品，却被迷思误导了。" },
      { text: "怎么说呢？" },
      { text: "❌ 毛孔可以「收缩」——毛孔大小由基因决定，只能暂时改善外观，不能真正缩小。" },
      { text: "❌ 天然 = 安全——很多天然成分也有刺激性和毒性（如精油、花粉）。" },
      { text: "❌ 一天见效的产品——要么含违禁成分，要么是心理作用。" },
      { text: "❌ 排毒面膜可以「排毒」——皮肤没有「排毒」功能，那是肝脏的工作。" },
      { heading: "🤔 重点整理", text: "✅ 用科学的眼光看待护肤\n✅ 不要被夸张的广告语骗了\n✅ 选择有研究支持的成分\n❌ 不要相信「一天见效」的产品\n❌ 不要挤痘痘——会留下疤痕和色素沉着" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-020",
    title: "敏感肌护理：你真的补对了吗？",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "14 Apr 2025",
    readTime: "3 min",
    excerpt: "敏感肌最重要的护肤原则：精简和温和。不是不能护肤，只是需要更聪明地选择。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#2f6a7d",
    body: [
      { text: "敏感肌最重要的护肤原则：精简和温和。不是不能护肤，只是需要更聪明地选择。" },
      { text: "也就是说——" },
      { text: "新产品先在耳后或手腕内侧试用 24–48 小时——确认没有反应再上脸。" },
      { text: "修复屏障的成分：神经酰胺、泛醇（B5）、积雪草、透明质酸——这些是敏感肌的好朋友。" },
      { text: "常见刺激成分：香精、酒精、高浓度酸类、精油、防腐剂。敏感肌需要避开这些。" },
      { heading: "🩹 重点整理", text: "✅ 精简产品——越少越好，给皮肤喘息的空间\n✅ 选择标注「fragrance-free」的产品\n✅ 新产品一定要先试用\n❌ 不要频繁更换产品——给皮肤适应的时间\n❌ 不要用过热的水洗脸——会破坏屏障" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-021",
    title: "男性护肤的真相，和你想的不一样",
    kicker: "Supplement truths",
    category: "Ingredient",
    date: "08 Dec 2025",
    readTime: "3 min",
    excerpt: "男性护肤不需要很复杂——基础三步就足够。但很多男性觉得护肤「不够男子汉」。",
    cover: "/editorial/story-brightening.png",
    accent: "#a62f4f",
    body: [
      { text: "男性护肤不需要很复杂——基础三步就足够。但很多男性觉得护肤「不够男子汉」。" },
      { text: "怎么说呢？" },
      { text: "基础三步：温和洁面 + 保湿 + 防晒。3 分钟搞定。" },
      { text: "剃须后选择不含酒精的须后产品以减少刺激——酒精会让皮肤更干更敏感。" },
      { text: "防晒不是「女生才做的事」——它是预防皮肤癌最有效的方式。男性皮肤癌风险其实比女性更高。" },
      { heading: "👨 重点整理", text: "✅ 洁面 + 保湿 + 防晒三步足够\n✅ 防晒是预防皮肤癌最有效的方式\n✅ 剃须后用温和的须后产品\n❌ 不要用肥皂洗脸——太刺激了\n❌ 不要忽视皮肤异常——及时看医生" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-022",
    title: "蛋白质摄入：药师的实用小课堂",
    kicker: "Kris supplement notes",
    category: "Clinical",
    date: "29 Dec 2025",
    readTime: "3 min",
    excerpt: "蛋白质是肌肉修复和生长的基础——但很多亚洲人长期蛋白质摄取不足。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#2fa66b",
    body: [
      { text: "蛋白质是肌肉修复和生长的基础——但很多亚洲人长期蛋白质摄取不足。" },
      { text: "有没有想过为什么？" },
      { text: "优质来源：鸡蛋、鱼类、鸡肉、牛奶、豆制品。每餐都应该有足够的蛋白质。" },
      { text: "40 岁以后肌肉量每 10 年约减少 3–8%——这就是为什么中老年人更容易跌倒和骨折。" },
      { text: "老年人每天建议摄取约 1.0–1.2g 每公斤体重的蛋白质——比年轻人需要更多。" },
      { heading: "💪 重点整理", text: "✅ 每餐都应该有足够的蛋白质——均匀分布比一次性大量更好\n✅ 运动后 30–60 分钟内摄取效果最佳\n✅ 乳清蛋白是方便的补充方式\n❌ 不是只有健身才需要蛋白质\n❌ 不要只靠蛋白粉——天然食物更好" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-023",
    title: "积雪草入门第一课，别再走弯路",
    kicker: "Kris supplement notes",
    category: "Editorial",
    date: "31 Jan 2026",
    readTime: "3 min",
    excerpt: "CICA 产品为什么这么火？因为积雪草（Centella Asiatica）真的有用——在亚洲已经有悠久的使用历史。",
    cover: "/editorial/hero.jpg",
    accent: "#6a5a8a",
    body: [
      { text: "CICA 产品为什么这么火？因为积雪草（Centella Asiatica）真的有用——在亚洲已经有悠久的使用历史。" },
      { text: "先来个基础课。" },
      { text: "CICA 产品适合用来做「皮肤急救」——晒后、过敏后都可以使用。" },
      { text: "积雪草可以帮助修复受损的皮肤屏障——对敏感肌和痘痘肌特别友好。" },
      { text: "积雪草含有积雪草苷和羟基积雪草苷等活性成分——帮助促进胶原蛋白合成、舒缓发炎。" },
      { heading: "🌿 重点整理", text: "✅ 舒缓 + 修复双重功效\n✅ 适合敏感肌和痘痘肌\n✅ 晒后急救的好选择\n❌ 不是所有 CICA 产品浓度都够\n❌ 单靠积雪草不能解决所有皮肤问题" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-024",
    title: "一文读懂锌与皮肤",
    kicker: "Kris supplement notes",
    category: "Supplement",
    date: "22 Feb 2026",
    readTime: "3 min",
    excerpt: "痘痘一直好不了？也许你缺的不是祛痘产品，而是锌——一种常被忽略的矿物质。",
    cover: "/products/fortress-plus-1.png",
    accent: "#b07c2f",
    body: [
      { text: "痘痘一直好不了？也许你缺的不是祛痘产品，而是锌——一种常被忽略的矿物质。" },
      { text: "但问题来了。" },
      { text: "富含锌的食物：牡蛎（锌含量最高）、红肉、南瓜子、鹰嘴豆、腰果。" },
      { text: "研究表明锌可以帮助减少痘痘的炎症、促进伤口愈合、调节皮脂分泌。" },
      { text: "葡萄糖酸锌或吡啶甲酸锌的吸收率较好——不要空腹服用高剂量锌，会引起恶心。" },
      { heading: "⚡ 重点整理", text: "✅ 缺锌的人更容易出现皮肤问题\n✅ 食补优先——牡蛎是锌的最佳来源\n✅ 搭配维生素 C 可以提高吸收\n❌ 不要长期高剂量补充——会干扰铜吸收\n❌ 不要以为痘痘只是表面问题——内部营养也很重要" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "好的配方，自己会说话。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-025",
    title: "先别急着买Omega-3",
    kicker: "Kris supplement notes",
    category: "Ingredient",
    date: "15 Jan 2025",
    readTime: "3 min",
    excerpt: "鱼油不只是「保养心血管」——Omega-3 对皮肤、大脑和关节都有重要影响。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#a65a2f",
    body: [
      { text: "鱼油不只是「保养心血管」——Omega-3 对皮肤、大脑和关节都有重要影响。" },
      { text: "怎么说呢？" },
      { text: "Omega-3 对心血管健康、大脑功能和关节健康都有帮助——是「全身性」的营养素。" },
      { text: "EPA 在抗炎方面可能比 DHA 更有效——对痘痘和湿疹的炎症有帮助。" },
      { text: "好的鱼油不应该有很重的鱼腥味——有腥味可能已经氧化，氧化的鱼油反而有害。" },
      { heading: "🐟 重点整理", text: "✅ EPA 在抗炎方面更有效——痘痘/湿疹患者可以关注\n✅ 选择经过重金属检测和氧化检测的产品\n✅ 冷藏保存可以延缓氧化\n❌ 不是所有鱼油纯度都一样——看 EPA+DHA 含量\n❌ 有腥味的鱼油可能已经氧化——不建议服用" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-026",
    title: "肠道健康：你真的补对了吗？",
    kicker: "Kris supplement notes",
    category: "Clinical",
    date: "30 Jul 2025",
    readTime: "3 min",
    excerpt: "皮肤是肠道的下游——肠道健康直接影响皮肤状态。很多人花大钱买护肤品，却忽略了肠道。",
    cover: "/editorial/story-brightening.png",
    accent: "#2f6a7d",
    body: [
      { text: "皮肤是肠道的下游——肠道健康直接影响皮肤状态。很多人花大钱买护肤品，却忽略了肠道。" },
      { text: "怎么说呢？" },
      { text: "膳食纤维是肠道菌群的「食物」——不够的话有益菌会饿死。大多数人每天膳食纤维不到建议量的一半。" },
      { text: "发酵食物（酸奶、泡菜、味噌）是天然的益生菌来源——比补充剂更便宜也更自然。" },
      { text: "肠道菌群失衡会导致全身性炎症——皮肤是受害者之一。痘痘、湿疹、暗沉都可能和肠道有关。" },
      { heading: "🦠 重点整理", text: "✅ 每天摄取足够的膳食纤维——蔬菜、水果、全谷物\n✅ 发酵食物是天然的益生菌来源\n✅ 多喝水——帮助膳食纤维发挥作用\n❌ 不要过度使用抗菌产品——会破坏菌群\n❌ 不要忽视肠道不适——可能是菌群失衡的信号" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-027",
    title: "祛痘全攻略的三个冷知识",
    kicker: "Supplement truths",
    category: "Ingredient",
    date: "16 Nov 2025",
    readTime: "3 min",
    excerpt: "痘痘的成因很复杂——荷尔蒙、细菌、炎症、饮食都可能是因素。治疗需要耐心，通常需要 6–8 周。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#a62f4f",
    body: [
      { text: "痘痘的成因很复杂——荷尔蒙、细菌、炎症、饮食都可能是因素。治疗需要耐心，通常需要 6–8 周。" },
      { text: "先来看看研究怎么说。" },
      { text: "过氧化苯甲酰可以杀死痤疮丙酸杆菌——但可能刺激皮肤，从低浓度开始。" },
      { text: "痘痘治疗的核心是「控制」而不是「根治」——需要长期管理。" },
      { text: "水杨酸（BHA）适合黑头和粉刺——脂溶性可以深入毛孔。" },
      { text: "外用 A 醇可以帮助预防毛孔堵塞——但需要建立耐受。" },
      { heading: "💪 重点整理", text: "✅ 找出痘痘的成因才能对症下药\n✅ 给产品足够的时间——6–8 周\n✅ 保持耐心——痘痘治疗是一场马拉松\n❌ 不要挤痘痘——会留下疤痕和色素沉着\n❌ 不要过度清洁——会加重炎症" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-028",
    title: "维生素D入门第一课，别再走弯路",
    kicker: "Clinical notes",
    category: "Editorial",
    date: "31 Aug 2025",
    readTime: "3 min",
    excerpt: "很多人以为马来西亚天天有太阳，就不会缺 Vitamin D。其实刚好相反——我们反而比温带国家的人更容易缺乏。",
    cover: "/editorial/hero.jpg",
    accent: "#2fa66b",
    body: [
      { text: "很多人以为马来西亚天天有太阳，就不会缺 Vitamin D。其实刚好相反——我们反而比温带国家的人更容易缺乏。" },
      { text: "先来看看研究怎么说。" },
      { text: "Vitamin D 进入身体后，需要经过肝脏、肾脏转化，最后变成活性的 calcitriol。它会和细胞里的 VDR 结合，再向细胞发出讯号——影响超过 200 个基因的表达。" },
      { text: "SEANUTS 全国调查显示，约 47.5% 的 4–12 岁儿童 Vitamin D 水平不足。吉隆坡一项针对小学生的研究更发现：35.3% Vitamin D 缺乏、37.1% 不足。" },
      { text: "Vitamin D 不只是帮助钙吸收。它在免疫调节、情绪稳定、肌肉功能方面都扮演重要角色。缺 D 的人更容易疲倦、情绪低落。" },
      { heading: "☀️ 重点整理", text: "✅ 适量户外活动，让皮肤接触阳光——每天 15–20 分钟\n✅ 多摄取富含 Vitamin D 的食物——三文鱼、沙丁鱼、鸡蛋黄、强化牛奶\n✅ 如果很少晒太阳，考虑补充 Vitamin D3（胆钙化醇）\n❌ 不要以为吃多就补多——Vitamin D 是脂溶性的，过量会积累在体内\n❌ 不要只靠防晒霜——SPF 再高也不能替代阳光合成 Vitamin D" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "有问题欢迎留言区讨论！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-029",
    title: "搞懂压力管理，别再交智商税",
    kicker: "Supplement truths",
    category: "Ingredient",
    date: "27 Apr 2025",
    readTime: "3 min",
    excerpt: "压力会直接反映在你的皮肤上。不是比喻，是科学——皮质醇是皮肤的「隐形敌人」。",
    cover: "/products/fortress-plus-1.png",
    accent: "#6a5a8a",
    body: [
      { text: "压力会直接反映在你的皮肤上。不是比喻，是科学——皮质醇是皮肤的「隐形敌人」。" },
      { text: "先来个基础课。" },
      { text: "压力触发皮质醇释放——导致痘痘爆发、湿疹发作、加速衰老和脱发。" },
      { text: "管理压力的方法：规律运动、冥想、深呼吸、充足睡眠、社交支持。" },
      { text: "长期压力还会导致毛囊提前进入休止期——这就是为什么压力大的时候掉头发特别多。" },
      { heading: "😰 重点整理", text: "✅ 规律运动是最好的压力管理工具——每天 30 分钟\n✅ 充足睡眠是压力管理的基础\n✅ 冥想和深呼吸可以快速降低皮质醇\n❌ 不要指望护肤品来抵消压力的伤害\n❌ 不要忽视持续的压力——它会影响全身健康" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "💬 你还知道什么关于压力管理的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-030",
    title: "睡眠与皮肤的七个冷知识",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "10 Jan 2025",
    readTime: "3 min",
    excerpt: "睡眠是最好的免费护肤品。这不是鸡汤，是科学——你熬的每一个夜，都在你的脸上记账。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#b07c2f",
    body: [
      { text: "睡眠是最好的免费护肤品。这不是鸡汤，是科学——你熬的每一个夜，都在你的脸上记账。" },
      { text: "简单来说：" },
      { text: "睡眠期间身体会进行细胞修复、胶原蛋白重建和炎症调节——这是护肤品做不到的「内部修复」。" },
      { text: "睡眠不足会导致皮质醇升高——引发炎症、痘痘爆发和加速衰老。" },
      { text: "最佳睡眠时间是 7–8 小时——不是「睡够就行」，质量也很重要。" },
      { text: "长期睡眠不足还会导致黑眼圈加重、肤色暗沉、免疫力下降——影响远不止皮肤。" },
      { heading: "😴 重点整理", text: "✅ 每天 7–8 小时高质量睡眠\n✅ 睡前 1 小时避免屏幕蓝光\n✅ 保持规律的睡眠时间——比「睡够 8 小时」更重要\n❌ 不要熬夜后指望护肤品来补救——治标不治本\n❌ 下午 2 点后尽量避免咖啡因" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "你有试过睡眠与皮肤相关的产品吗？我想听听你的分享。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-031",
    title: "别再乱买热带气候护肤产品了",
    kicker: "Supplement truths",
    category: "Ingredient",
    date: "22 Mar 2025",
    readTime: "3 min",
    excerpt: "在马来西亚这样的热带气候，护肤需要做一些调整——高温高湿不代表不需要保湿。",
    cover: "/editorial/story-brightening.png",
    accent: "#a65a2f",
    body: [
      { text: "在马来西亚这样的热带气候，护肤需要做一些调整——高温高湿不代表不需要保湿。" },
      { text: "但问题来了。" },
      { text: "室内空调环境反而可能让皮肤变干——需要注意保湿。" },
      { text: "防晒选择防水耐汗的配方——SPF30+ 广谱防护足够日常使用。" },
      { text: "质地选择轻薄的凝胶或乳液——厚重面霜在热带气候容易闷痘。" },
      { heading: "🌴 重点整理", text: "✅ 轻薄质地更适合热带气候\n✅ 防水耐汗的防晒配方\n✅ 空调房内需要额外保湿\n❌ 不要因为出汗就忽略保湿\n❌ 不要过度清洁——出汗后温和清洁就好" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-032",
    title: "关于视黄醇，这些误区你踩了几个？",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "03 Aug 2025",
    readTime: "3 min",
    excerpt: "A 醇入门的「翻车」经历，几乎每个人都经历过。脱皮、泛红、干燥——其实这些都是可以避免的。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "A 醇入门的「翻车」经历，几乎每个人都经历过。脱皮、泛红、干燥——其实这些都是可以避免的。" },
      { text: "简单来说：" },
      { text: "「皮肤转换期」是正常的——通常在开始使用的前 2–4 周出现。不是过敏，是皮肤在适应。" },
      { text: "三明治法：先涂保湿→A 醇→再涂保湿——可以大幅减少刺激。" },
      { text: "不是每个人都需要 A 醇——如果你的皮肤已经很好，维持现状就好。" },
      { heading: "🌙 重点整理", text: "✅ 三明治法可以减少刺激\n✅ 给皮肤足够的适应时间\n❌ 不要频繁使用——一周 2–3 次足够\n❌ 不要和其他强效活性成分叠加" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-033",
    title: "化妆品安全入门第一课，别再走弯路",
    kicker: "Pharmacist explains",
    category: "Supplement",
    date: "29 Jun 2025",
    readTime: "3 min",
    excerpt: "化妆品过期后使用可能导致细菌滋生和皮肤过敏——但很多人不知道怎么判断是否过期。",
    cover: "/editorial/hero.jpg",
    accent: "#a62f4f",
    body: [
      { text: "化妆品过期后使用可能导致细菌滋生和皮肤过敏——但很多人不知道怎么判断是否过期。" },
      { text: "怎么说呢？" },
      { text: "存放环境很重要——高温高湿会加速变质。不要放在浴室或车内暴晒。" },
      { text: "如果产品出现异味、变色、质地改变——即使没到保质期也应该丢弃。" },
      { text: "PAO 符号（如 12M）表示开封后 12 个月内使用完。没有 PAO 的产品建议开封后 12 个月内用完。" },
      { heading: "💄 重点整理", text: "✅ 定期清理化妆包——每 3 个月检查一次\n✅ 存放在阴凉干燥处\n✅ 用小勺取用罐装产品——避免手指污染\n❌ 不要放在浴室——高温高湿加速变质\n❌ 不要用手直接挖罐装产品" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "你有试过化妆品安全相关的产品吗？我想听听你的分享。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-034",
    title: "保湿真相入门第一课，别再走弯路",
    kicker: "Pharmacist explains",
    category: "Editorial",
    date: "03 Feb 2026",
    readTime: "3 min",
    excerpt: "保湿不是「涂一层 cream 就好」——关键是选对成分。油性皮肤也需要保湿。",
    cover: "/products/fortress-plus-1.png",
    accent: "#2fa66b",
    body: [
      { text: "保湿不是「涂一层 cream 就好」——关键是选对成分。油性皮肤也需要保湿。" },
      { text: "有没有想过为什么？" },
      { text: "保湿成分分三类：保湿剂（吸水，如透明质酸）、润肤剂（软化，如神经酰胺）、封闭剂（锁水，如凡士林）。" },
      { text: "神经酰胺是润肤剂——帮助修复皮肤屏障，是敏感肌的首选。" },
      { text: "透明质酸是保湿剂——需要搭配封闭剂才能锁住水分。单独用可能在干燥环境下反而吸走水分。" },
      { heading: "💧 重点整理", text: "✅ 保湿剂 + 封闭剂搭配效果最好\n✅ 油性皮肤选轻薄的凝胶或乳液\n✅ 干燥环境需要更强的封闭剂\n❌ 不是所有保湿产品都适合你的肤质\n❌ 不要只用透明质酸——需要封闭剂锁水" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "💬 你还知道什么关于保湿真相的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-035",
    title: "关节保健：药师的实用小课堂",
    kicker: "Kris supplement notes",
    category: "Supplement",
    date: "13 Dec 2025",
    readTime: "3 min",
    excerpt: "很多人关节痛就开始吃关节保健品。但你有没有想过：关节到底是什么？你补的成分真的对症吗？",
    cover: "/products/epsilon-cream-1.png",
    accent: "#6a5a8a",
    body: [
      { text: "很多人关节痛就开始吃关节保健品。但你有没有想过：关节到底是什么？你补的成分真的对症吗？" },
      { text: "先来看看研究怎么说。" },
      { text: "Glucosamine 研究显示约 50% 的人服用后没有明显效果——选对成分很重要。" },
      { text: "Osteoliv 蕴含四大核心成分：活性胶原蛋白肽、海藻钙、维生素 D3、维生素 K2。四者协同作用，从不同层面支持关节健康。" },
      { text: "关节就像一部汽车。软骨是缓冲垫，滑液是润滑油。你不能只换一个零件——需要全面保养。" },
      { heading: "🦴 重点整理", text: "✅ 关节一开始觉得沙沙/卡卡的时候就要开始保健了——预防比治疗便宜\n✅ 2 型胶原蛋白的效果是 Glucosamine 的 2 倍——选对成分\n✅ K2 + D3 + 钙是黄金组合\n❌ 不要等痛到不行才来补——软骨磨损是不可逆的\n❌ 不要只看品牌广告，要看具体成分和剂量" },
      { text: "K2 的作用是「引钙入骨」——没有 K2，补再多钙可能都白费。钙会沉积在血管里而不是骨骼中。" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoGard——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-036",
    title: "这个玫瑰痤疮问题，太多人忽略了",
    kicker: "Supplement truths",
    category: "Ingredient",
    date: "12 Jan 2025",
    readTime: "3 min",
    excerpt: "玫瑰痤疮（Rosacea）不是「皮肤敏感」这么简单——它是一种血管性皮肤问题，需要正确对待。",
    cover: "/editorial/story-brightening.png",
    accent: "#b07c2f",
    body: [
      { text: "玫瑰痤疮（Rosacea）不是「皮肤敏感」这么简单——它是一种血管性皮肤问题，需要正确对待。" },
      { text: "怎么说呢？" },
      { text: "壬二酸是玫瑰痤疮的常用外用成分——可以帮助减少炎症和泛红。" },
      { text: "触发因素：热食、辛辣食物、酒精、日晒、压力、极端温度。每个人的触发因素可能不同。" },
      { text: "主要表现为面部中央持续性泛红、可见血管丝、偶尔出现丘疹——容易和痘痘混淆。" },
      { heading: "🌹 重点整理", text: "✅ 使用温和无香料的产品——越简单越好\n✅ 选择矿物防晒（氧化锌）——化学防晒可能刺激\n✅ 记录触发因素日记——了解自己的「地雷」\n❌ 避免含酒精、薄荷、桉树油的产品\n❌ 严重时需要看皮肤科医生——不要自己乱搞" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-037",
    title: "这个防晒问题，太多人忽略了",
    kicker: "Pharmacist explains",
    category: "Ingredient",
    date: "07 Feb 2025",
    readTime: "3 min",
    excerpt: "你以为涂了防晒就万事大吉了？其实大部分人防晒用量都不够——SPF50 可能只有 SPF10 的效果。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#a65a2f",
    body: [
      { text: "你以为涂了防晒就万事大吉了？其实大部分人防晒用量都不够——SPF50 可能只有 SPF10 的效果。" },
      { text: "先来个基础课。" },
      { text: "出汗、游泳、擦脸都会降低防晒效果——防水配方也只能维持 40–80 分钟。" },
      { text: "SPF 测试是基于每平方厘米 2mg 的用量——用量不够的话，SPF50 实际上只有 SPF10–15 的防护力。" },
      { text: "脸部需要约 1/4 茶匙（约 1.2ml）——大约两个手指的长度。大部分人只涂了标准量的 1/4 到 1/2。" },
      { heading: "☀️ 重点整理", text: "✅ 脸部：两个手指长度的量\n✅ 每 2 小时补擦，出汗/游泳后立即补擦\n❌ 不要只擦薄薄一层——用量不够等于没擦\n❌ 不要忘记耳朵、脖子和手背" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-038",
    title: "这个面膜问题，太多人忽略了",
    kicker: "Kris notes",
    category: "Ingredient",
    date: "29 Oct 2025",
    readTime: "3 min",
    excerpt: "面膜不是敷越久越好——10–15 分钟就够了。敷太久反而会倒吸皮肤水分。",
    cover: "/editorial/hero.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "面膜不是敷越久越好——10–15 分钟就够了。敷太久反而会倒吸皮肤水分。" },
      { text: "先来个基础课。" },
      { text: "面膜是锦上添花，不是急救神器——日常护肤才是基础。" },
      { text: "敷太久面膜纸会变干，开始倒吸皮肤水分——得不偿失。" },
      { text: "面膜的主要功能是封闭性补水——让精华成分在短时间内更好地渗透。" },
      { heading: "🧖 重点整理", text: "✅ 10–15 分钟就够了——不要敷到面膜纸干掉\n✅ 敏感肌选成分简单的——越少越好\n✅ 敷完后涂抹保湿产品锁住水分\n❌ 不要敷着面膜睡觉——会倒吸水分\n❌ 不要天天敷——过度水合反而伤皮肤" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Mist——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-039",
    title: "别再乱买湿疹产品了",
    kicker: "Clinical notes",
    category: "Editorial",
    date: "10 Sep 2025",
    readTime: "3 min",
    excerpt: "湿疹不是「皮肤干燥」这么简单。它是一种屏障疾病——皮肤的「城墙」出了问题。",
    cover: "/products/fortress-plus-1.png",
    accent: "#a62f4f",
    body: [
      { text: "湿疹不是「皮肤干燥」这么简单。它是一种屏障疾病——皮肤的「城墙」出了问题。" },
      { text: "但问题来了。" },
      { text: "网路神 cream 又爆雷了。12 岁男童连续涂抹两个月后体重暴增六公斤——含强效类固醇的产品短期见效但长期伤害巨大。" },
      { text: "湿疹皮肤流失约三倍于健康皮肤的水分——形成痒→抓→发作的恶性循环。" },
      { text: "Epsilon Ultra Soothing Cream 以 3:1:1 的生理比例输送神经酰胺 NP、AP 和 EOP——修复屏障，不是「止痒」。" },
      { heading: "🛡️ 重点整理", text: "✅ 湿疹的治疗核心是修复屏障，不是「止痒」\n✅ 神经酰胺 3:1:1 比例是关键——选对产品\n✅ 棉质衣物比合成纤维更适合湿疹患者\n❌ 不要用含类固醇的「神cream」——短期见效但长期伤害\n❌ 不要听网红说「全天然无副作用」——天然不等于安全\n❌ 不要抓挠——会加重炎症和感染风险" },
      { text: "问题产品三大特征：全部天然却立马见效、一个 cream 解决所有问题、一停用就反弹。" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-040",
    title: "关于益生菌，这些误区你踩了几个？",
    kicker: "Supplement truths",
    category: "Editorial",
    date: "06 Feb 2025",
    readTime: "3 min",
    excerpt: "皮肤是肠道的下游。这句话不是鸡汤，是科学——很多皮肤问题可能要从肠道开始解决。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#2fa66b",
    body: [
      { text: "皮肤是肠道的下游。这句话不是鸡汤，是科学——很多皮肤问题可能要从肠道开始解决。" },
      { text: "怎么说呢？" },
      { text: "肠脑皮肤轴——肠道炎症、营养状况和微生物组平衡会直接反映在皮肤上。肠道菌群失衡可能导致全身性炎症。" },
      { text: "NUCA® RevoBiotic 将益生元、益生菌、后生元、消化酶合并在一包中——三者协同比单一成分更有效。" },
      { text: "膳食纤维是肠道菌群的「食物」——不够的话有益菌会饿死。大多数人每天膳食纤维摄取量不到建议的一半。" },
      { heading: "🦠 重点整理", text: "✅ 益生菌 + 益生元 + 后生元三者搭配效果最好\n✅ 皮肤问题反复发作，也许该看看肠道\n✅ 发酵食物（酸奶、泡菜、味噌）是天然的益生菌来源\n❌ 不是所有益生菌菌株都一样——要看具体研究支持的菌株\n❌ 不要指望一包益生菌就解决所有问题——需要持续摄取" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-041",
    title: "你真的了解水杨酸吗？",
    kicker: "Supplement truths",
    category: "Clinical",
    date: "21 Mar 2025",
    readTime: "3 min",
    excerpt: "水杨酸（Salicylic Acid / BHA）是油痘肌的救星——但用错方式反而会刺激皮肤。",
    cover: "/editorial/story-brightening.png",
    accent: "#6a5a8a",
    body: [
      { text: "水杨酸（Salicylic Acid / BHA）是油痘肌的救星——但用错方式反而会刺激皮肤。" },
      { text: "有没有想过为什么？" },
      { text: "一般建议浓度 0.5–2%，从低浓度开始。油痘肌可以每天使用，干性或敏感肌建议每周 2–3 次。" },
      { text: "水杨酸是脂溶性的——可以深入毛孔内部溶解堵塞的油脂和老废角质。这是它比果酸更适合油痘肌的原因。" },
      { text: "水杨酸最初来自柳树皮——天然来源，但现在通过合成可以获得更纯更稳定的版本。" },
      { heading: "🧪 重点整理", text: "✅ 脂溶性——能深入毛孔清洁\n✅ 油痘肌的好朋友——黑头粉刺的克星\n✅ 低浓度（0.5%）就可以有效果\n❌ 不要和高浓度果酸同时使用——会过度去角质\n❌ 敏感肌要从低浓度开始，每周 1–2 次" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-042",
    title: "一文读懂神经酰胺",
    kicker: "Kris supplement notes",
    category: "Ingredient",
    date: "25 Nov 2025",
    readTime: "3 min",
    excerpt: "神经酰胺（Ceramide）是皮肤屏障的核心成分——少了它，皮肤就像没关门的房子，水分一直流失。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#b07c2f",
    body: [
      { text: "神经酰胺（Ceramide）是皮肤屏障的核心成分——少了它，皮肤就像没关门的房子，水分一直流失。" },
      { text: "怎么说呢？" },
      { text: "屏障受损会导致经皮水分流失（TEWL）增加——皮肤越干→屏障越差→越干的恶性循环。" },
      { text: "Epsilon Ultra Soothing Cream 就是用这个比例来修复屏障的——神经酰胺 NP、AP 和 EOP。" },
      { text: "神经酰胺占皮肤屏障脂质约 50%——是「城墙」的主要建筑材料。" },
      { heading: "🧬 重点整理", text: "✅ 3:1:1 比例是关键——不是所有产品都对\n✅ 修复屏障是敏感肌和湿疹的第一步\n✅ 搭配透明质酸效果更好——一个锁水一个补水\n❌ 不是所有含神经酰胺的产品比例都对\n❌ 不要只看「含有神经酰胺」——要看排在成分表第几位" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-043",
    title: "关于糖与皮肤老化，这些误区你踩了几个？",
    kicker: "Supplement truths",
    category: "Supplement",
    date: "16 Jan 2026",
    readTime: "3 min",
    excerpt: "你喝的那杯奶茶，可能正在让你的脸加速老化——糖是皮肤的隐形杀手。",
    cover: "/editorial/hero.jpg",
    accent: "#a65a2f",
    body: [
      { text: "你喝的那杯奶茶，可能正在让你的脸加速老化——糖是皮肤的隐形杀手。" },
      { text: "怎么说呢？" },
      { text: "高糖饮食引发胰岛素飙升，进而刺激皮脂分泌和炎症反应——痘痘的元凶之一。" },
      { text: "WHO 建议每天添加糖摄入不超过 25g——一杯奶茶就可能超标。" },
      { text: "过量糖摄入会导致糖化反应（glycation）——糖分子附着在胶原蛋白上使其变硬变脆，失去弹性。" },
      { heading: "🍬 重点整理", text: "✅ 用水果代替甜食——天然糖分有纤维缓冲\n✅ 看营养标签——隐藏的糖分很多（酱料、饮料、面包）\n✅ 选择低 GI 食物——血糖稳定对皮肤更好\n❌ 不是说完全不能吃糖——适量就好\n❌ 不要被「无糖」标签骗了——可能只是没加蔗糖" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-044",
    title: "维生素D的五个冷知识",
    kicker: "Pharmacist explains",
    category: "Clinical",
    date: "14 Apr 2025",
    readTime: "3 min",
    excerpt: "你有没有注意到，冬天特别容易感冒、疲倦、情绪低落？可能跟 Vitamin D 有关。",
    cover: "/products/fortress-plus-1.png",
    accent: "#2f6a7d",
    body: [
      { text: "你有没有注意到，冬天特别容易感冒、疲倦、情绪低落？可能跟 Vitamin D 有关。" },
      { text: "但问题来了。" },
      { text: "冬天阳光角度低，UVB 无法有效到达地面，皮肤合成 Vitamin D 的效率大幅下降。" },
      { text: "Vitamin D 的「窗口期」：从 11 月到 3 月，大部分地区几乎无法通过阳光合成足够的 Vitamin D。" },
      { text: "研究显示 Vitamin D 不足与呼吸道感染风险增加有关——补充 Vitamin D 可以降低上呼吸道感染的几率。" },
      { heading: "☀️ 重点整理", text: "✅ 冬天特别需要关注 Vitamin D 摄取\n✅ 补充 Vitamin D3 是最有效的方式\n❌ 不要等症状严重才来补——预防性补充更重要\n❌ 不要只在冬天补——全年都需要" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "💬 你还知道什么关于维生素D的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-045",
    title: "为什么你的湿疹一直没效？",
    kicker: "Kris supplement notes",
    category: "Clinical",
    date: "22 Apr 2025",
    readTime: "3 min",
    excerpt: "你有没有发现，压力大的时候湿疹特别容易发作？这不是巧合——肠脑皮肤轴在作怪。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#a62f4f",
    body: [
      { text: "你有没有发现，压力大的时候湿疹特别容易发作？这不是巧合——肠脑皮肤轴在作怪。" },
      { text: "有没有想过为什么？" },
      { text: "环境因素（尘螨、宠物毛发、花粉）也是常见的触发因素——需要逐一排查。" },
      { text: "压力会触发皮质醇释放——皮质醇升高会抑制免疫系统，导致湿疹发作。" },
      { text: "湿疹的管理需要长期坚持——保湿是基础，每天至少 2 次。" },
      { heading: "🛡️ 重点整理", text: "✅ 每天至少保湿 2 次——沐浴后立即涂抹效果最好\n✅ 记录发作日记——找出你的触发因素\n❌ 不要自行使用类固醇药膏——需要医生指导\n❌ 不要忽视压力管理——它直接影响皮肤" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "你有试过湿疹相关的产品吗？我想听听你的分享。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-046",
    title: "辅酶Q10入门第一课，别再走弯路",
    kicker: "Pharmacist explains",
    category: "Supplement",
    date: "10 Mar 2025",
    readTime: "3 min",
    excerpt: "辅酶 Q10（CoQ10）是细胞能量工厂的核心成分——随着年龄增长，身体合成它的能力会下降。",
    cover: "/editorial/story-brightening.png",
    accent: "#2fa66b",
    body: [
      { text: "辅酶 Q10（CoQ10）是细胞能量工厂的核心成分——随着年龄增长，身体合成它的能力会下降。" },
      { text: "先来个基础课。" },
      { text: "它也是一种强大的抗氧化剂——可以帮助保护细胞免受自由基伤害。" },
      { text: "对心血管健康也有潜在好处——心脏是 CoQ10 需求量最高的器官。" },
      { text: "CoQ10 参与细胞能量产生——线粒体的「燃料」。没有它，细胞就没有能量。" },
      { heading: "❤️ 重点整理", text: "✅ CoQ10 对心脏和皮肤都有帮助\n✅ 30 岁以后合成能力下降——可能需要补充\n✅ 泛醇（Ubiquinol）比泛醌（Ubiquinone）吸收率更好\n❌ 不要和抗凝血药物同时使用——先咨询医生\n❌ 吸收率因配方而异——选择经过验证的产品" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "你有试过辅酶Q10相关的产品吗？我想听听你的分享。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-047",
    title: "乳制品与痘痘的七个冷知识",
    kicker: "Clinical notes",
    category: "Ingredient",
    date: "22 Jan 2026",
    readTime: "3 min",
    excerpt: "如果你痘痘一直反反复复，也许该试试减少乳制品——很多人不知道这两者的关联。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#6a5a8a",
    body: [
      { text: "如果你痘痘一直反反复复，也许该试试减少乳制品——很多人不知道这两者的关联。" },
      { text: "简单来说：" },
      { text: "酸奶和发酵乳制品的影响可能较小——发酵过程分解了部分 IGF-1。" },
      { text: "牛奶中的 IGF-1（类胰岛素生长因子）可以刺激皮脂分泌——痘痘形成的关键环节。" },
      { text: "脱脂牛奶的影响可能比全脂更大——加工过程改变了蛋白质结构，IGF-1 含量反而更高。" },
      { heading: "🥛 重点整理", text: "✅ 可以试试减少或排除乳制品 2–4 周观察变化\n✅ 酸奶是相对安全的替代——发酵过程改变了牛奶蛋白\n❌ 不是说所有人都要戒牛奶——观察自己的身体反应\n❌ 不要盲目跟风——每个人的情况不同" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-048",
    title: "关于姜黄，药师想说的七件事",
    kicker: "Clinical notes",
    category: "Ingredient",
    date: "28 Nov 2025",
    readTime: "3 min",
    excerpt: "姜黄不只是咖喱里的香料——它是一种强大的抗炎成分。但有一个问题：单独服用吸收率很低。",
    cover: "/editorial/hero.jpg",
    accent: "#b07c2f",
    body: [
      { text: "姜黄不只是咖喱里的香料——它是一种强大的抗炎成分。但有一个问题：单独服用吸收率很低。" },
      { text: "也就是说——" },
      { text: "Curcumin（姜黄素）需要搭配黑胡椒中的胡椒碱才能显著提高吸收——可以提高 2000%。" },
      { text: "研究表明姜黄对关节炎、消化问题和全身性炎症都有潜在帮助。" },
      { text: "Osteoliv 中就含有姜黄素——搭配其他成分协同作用。" },
      { heading: "🟡 重点整理", text: "✅ 搭配黑胡椒吸收率提高 2000%\n✅ 抗炎 + 抗氧化双重功效\n✅ 对关节和消化都有帮助\n❌ 不要单独服用姜黄粉——吸收率很低\n❌ 姜黄会让衣服和台面染色——小心使用" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoGard——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-049",
    title: "色素沉着：药师的实用小课堂",
    kicker: "Pharmacist explains",
    category: "Editorial",
    date: "11 Jul 2025",
    readTime: "3 min",
    excerpt: "防晒是所有色素治疗的基础——没有防晒，其他治疗效果都打折扣。但很多人忽略这一点。",
    cover: "/products/fortress-plus-1.png",
    accent: "#a65a2f",
    body: [
      { text: "防晒是所有色素治疗的基础——没有防晒，其他治疗效果都打折扣。但很多人忽略这一点。" },
      { text: "先来个基础课。" },
      { text: "如果外用效果不明显，化学焕肤或激光可以考虑——但术后护理很重要。" },
      { text: "外用成分：维生素 C（抗氧化+美白）、烟酰胺（抑制转运）、壬二酸（抑制酪氨酸酶）。" },
      { text: "传明酸适合黄褐斑——通过抑制纤溶酶原激活来减少色素。" },
      { text: "色素淡化需要时间——至少 3–6 个月才能看到明显变化。不要指望一周见效。" },
      { heading: "✨ 重点整理", text: "✅ 防晒是所有色素治疗的基础——不防晒其他都白做\n✅ 维 C + 烟酰胺 + 壬二酸是经典组合\n✅ 给皮肤足够的时间——3–6 个月\n❌ 不要指望一周见效——色素淡化需要耐心\n❌ 不要忽略防晒——紫外线会加重色素沉着" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-050",
    title: "烟酰胺：药师的实用小课堂",
    kicker: "Kris notes",
    category: "Ingredient",
    date: "29 Aug 2025",
    readTime: "3 min",
    excerpt: "烟酰胺（Niacinamide）是维生素 B3 的衍生物，一个超全能的护肤成分——但很多人用错了浓度。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#2f6a7d",
    body: [
      { text: "烟酰胺（Niacinamide）是维生素 B3 的衍生物，一个超全能的护肤成分——但很多人用错了浓度。" },
      { text: "有没有想过为什么？" },
      { text: "建议浓度在 2–5% 之间——10% 反而可能引起刺激和泛红。不是浓度越高越好。" },
      { text: "烟酰胺可以帮助控制皮脂分泌、缩小毛孔外观、强化皮肤屏障、改善色素沉着——几乎什么都能做。" },
      { text: "和维生素 C 可以一起使用——现代研究已经推翻了早期「不能同时用」的说法。" },
      { heading: "✨ 重点整理", text: "✅ 适合几乎所有肤质，包括敏感肌\n✅ 2–5% 浓度就可以看到效果\n✅ 早晚都可以使用——温和不刺激\n❌ 不是浓度越高越好——10% 可能反而刺激\n❌ 不要和高浓度酸类同时叠加——可能增加刺激风险" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-051",
    title: "玻尿酸入门第一课，别再走弯路",
    kicker: "Pharmacist explains",
    category: "Editorial",
    date: "18 May 2025",
    readTime: "3 min",
    excerpt: "玻尿酸可以吸收自身重量 1000 倍的水分——但用错方式反而会吸走皮肤的水分。",
    cover: "/editorial/story-brightening.png",
    accent: "#a62f4f",
    body: [
      { text: "玻尿酸可以吸收自身重量 1000 倍的水分——但用错方式反而会吸走皮肤的水分。" },
      { text: "有没有想过为什么？" },
      { text: "在干燥环境下单独使用玻尿酸可能反而吸走皮肤水分——需要搭配封闭剂。" },
      { text: "皮肤中的玻尿酸可以帮助维持含水量，让皮肤看起来饱满有弹性。但随着年龄增长，合成能力会下降。" },
      { text: "口服玻尿酸研究显示对皮肤水分和关节健康都有帮助——不只是外用有效。" },
      { heading: "💧 重点整理", text: "✅ 外用要搭配封闭剂（如面霜）锁住水分\n✅ 口服玻尿酸研究支持对皮肤和关节有益\n✅ 分子量越小渗透越深——但不一定越好\n❌ 干燥环境下单独用玻尿酸可能反而吸走水分\n❌ 不是所有玻尿酸产品浓度都够" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-052",
    title: "搞懂益生菌，别再交智商税",
    kicker: "Clinical notes",
    category: "Ingredient",
    date: "24 Mar 2025",
    readTime: "3 min",
    excerpt: "很多人以为益生菌只是「帮助消化」。其实它的影响力远超你的想象——从免疫到情绪到皮肤。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#2fa66b",
    body: [
      { text: "很多人以为益生菌只是「帮助消化」。其实它的影响力远超你的想象——从免疫到情绪到皮肤。" },
      { text: "也就是说——" },
      { text: "肠道菌群的数量超过人体细胞的总数——它们不是「寄生虫」，而是共生伙伴。" },
      { text: "不同菌株有不同的功能——Lactobacillus 和 Bifidobacterium 是研究最充分的两大类。" },
      { text: "Fortress 里的益生菌可以杀死超过 80% 痘痘细菌——外用益生菌也开始受到关注。" },
      { heading: "🦠 重点整理", text: "✅ 选择含有研究充分菌株的产品\n✅ 搭配膳食纤维效果更好\n❌ 不是所有益生菌都一样——菌株特异性很重要\n❌ 不要和热饮一起服用——高温会杀死活性菌" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "有问题欢迎留言区讨论！" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-053",
    title: "护肤顺序，正确打开方式在这里",
    kicker: "Pharmacist explains",
    category: "Supplement",
    date: "21 Oct 2025",
    readTime: "3 min",
    excerpt: "护肤顺序其实很简单——但很多人搞复杂了。你不需要十几步才能拥有好皮肤。",
    cover: "/editorial/hero.jpg",
    accent: "#6a5a8a",
    body: [
      { text: "护肤顺序其实很简单——但很多人搞复杂了。你不需要十几步才能拥有好皮肤。" },
      { text: "先来个基础课。" },
      { text: "质地从薄到厚、从水基到油基——这是为了让每一步都能被皮肤吸收。" },
      { text: "多余的产品反而可能增加刺激风险——不是越多越好。" },
      { text: "正确顺序：清洁 → 精华 → 面霜 → 防晒（白天）。核心只需要这 4 步。" },
      { heading: "📋 重点整理", text: "✅ 清洁 → 精华 → 面霜 → 防晒——4 步足够\n✅ 新产品一个一个加入——不要同时引入太多\n✅ 晚上可以省略防晒，加入 A 醇或酸类\n❌ 不要一次叠加太多活性成分——会打架\n❌ 不要过度清洁——会破坏屏障" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-054",
    title: "儿童护肤的二个冷知识",
    kicker: "Clinical notes",
    category: "Ingredient",
    date: "21 Feb 2025",
    readTime: "3 min",
    excerpt: "孩子的皮肤比成人薄——护肤品的选择原则就是：温和、简单。不需要大人的那些「进阶」产品。",
    cover: "/products/fortress-plus-1.png",
    accent: "#b07c2f",
    body: [
      { text: "孩子的皮肤比成人薄——护肤品的选择原则就是：温和、简单。不需要大人的那些「进阶」产品。" },
      { text: "简单来说：" },
      { text: "儿童皮肤屏障功能还不完善——过度清洁反而会伤害皮肤。" },
      { text: "日常只需要：温和清洁 + 基础保湿 + 防晒（6 个月以上）。" },
      { text: "物理防晒（氧化锌）对儿童来说更安全——不会被皮肤吸收。" },
      { heading: "👶 重点整理", text: "✅ 温和清洁 + 基础保湿 + 防晒\n✅ 物理防晒对儿童更安全\n✅ 选择专门为儿童设计的产品\n❌ 不要用成人产品给孩子——浓度和成分不适合\n❌ 不要给孩子用美白、抗老产品——没必要" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-055",
    title: "视黄醇的真相，和你想的不一样",
    kicker: "Kris supplement notes",
    category: "Ingredient",
    date: "03 Feb 2026",
    readTime: "3 min",
    excerpt: "A 醇（Retinol）是目前研究最充分的抗老成分之一。但使用不当反而会伤害皮肤——入门第一课：慢慢来。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#a65a2f",
    body: [
      { text: "A 醇（Retinol）是目前研究最充分的抗老成分之一。但使用不当反而会伤害皮肤——入门第一课：慢慢来。" },
      { text: "怎么说呢？" },
      { text: "从低浓度（0.25–0.3%）开始，每周 2–3 次，让皮肤慢慢建立耐受——通常需要 4–6 周。" },
      { text: "A 醇和 A 酸（Tretinoin）不同——A 醇需要在皮肤中转化才能起效，所以更温和。" },
      { text: "A 醇可以促进胶原蛋白生成、加速细胞更新、改善细纹和肤色不均——是抗老的「黄金标准」。" },
      { text: "使用后一定要保湿，白天一定要防晒——A 醇会让皮肤对紫外线更敏感。" },
      { heading: "🌙 重点整理", text: "✅ 从低浓度开始，每周 2–3 次\n✅ 使用后保湿 + 白天防晒是必须的\n✅ 搭配烟酰胺可以减少刺激\n❌ 不要一上来就用高浓度——会脱皮到你怀疑人生\n❌ 不要和高浓度酸类同时使用\n❌ 孕妇和哺乳期避免使用——有致畸风险" },
      { heading: "药师小贴士 💊", text: "💊 每个人的体质不同，适合别人的不一定适合你。" },
      { text: "有问题欢迎留言区讨论！" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-056",
    title: "关节保健的二个冷知识",
    kicker: "Kris supplement notes",
    category: "Ingredient",
    date: "24 Nov 2025",
    readTime: "3 min",
    excerpt: "怎么说呢？关节问题不是老年人才有的。很多人 30 岁就开始「沙沙」了。",
    cover: "/editorial/story-brightening.png",
    accent: "#2f6a7d",
    body: [
      { text: "怎么说呢？关节问题不是老年人才有的。很多人 30 岁就开始「沙沙」了。" },
      { text: "有没有想过为什么？" },
      { text: "久坐、缺乏运动、体重过重都会加速关节磨损。" },
      { text: "运动前后适当补充关节营养，可以减少运动损伤的风险。" },
      { text: "关节液的成分和滑膜的功能直接影响关节灵活性——不是只有软骨需要保养。" },
      { heading: "🦴 重点整理", text: "✅ 30 岁以后就该开始关注关节健康\n✅ 适度运动比完全不动对关节更好\n❌ 不要以为「痛就不要动」——适度活动反而有助于关节保养\n❌ 不要盲目跟风买关节保健品——看成分" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoGard——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-057",
    title: "一文读懂荷尔蒙与皮肤",
    kicker: "Clinical notes",
    category: "Ingredient",
    date: "12 Dec 2025",
    readTime: "3 min",
    excerpt: "你的荷尔蒙正在影响你的皮肤——月经周期、压力、年龄都在改变你的皮肤状态。很多人不知道这一点。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#a62f4f",
    body: [
      { text: "你的荷尔蒙正在影响你的皮肤——月经周期、压力、年龄都在改变你的皮肤状态。很多人不知道这一点。" },
      { text: "但问题来了。" },
      { text: "怀孕和更年期荷尔蒙变化会导致色素沉着和干燥——需要调整护肤策略。" },
      { text: "甲状腺问题也可能导致皮肤干燥、脱发、指甲变脆——如果症状持续，看医生检查。" },
      { text: "月经前黄体酮上升——皮脂分泌增加，痘痘更容易爆发。记录周期可以帮助预测。" },
      { heading: "🔬 重点整理", text: "✅ 记录月经周期和痘痘爆发的时间——找出规律\n✅ 如果怀疑荷尔蒙问题——看医生做检查\n✅ 不同荷尔蒙阶段需要不同的护肤策略\n❌ 不要自己乱吃调节荷尔蒙的保健品\n❌ 不要忽视持续的皮肤变化" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-058",
    title: "防晒的真相，和你想的不一样",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "11 May 2025",
    readTime: "3 min",
    excerpt: "很多人以为 SPF 越高越好。其实不完全是——SPF30 和 SPF50 的实际差距只有 1%。",
    cover: "/editorial/hero.jpg",
    accent: "#2fa66b",
    body: [
      { text: "很多人以为 SPF 越高越好。其实不完全是——SPF30 和 SPF50 的实际差距只有 1%。" },
      { text: "但问题来了。" },
      { text: "UVA 可以穿透玻璃和云层——室内靠窗也会晒黑。UVA 是导致皮肤老化和色素沉着的主要元凶。" },
      { text: "真正重要的不是 SPF 数字，而是有没有擦足够量（脸部约 1/4 茶匙）和有没有每两小时补擦一次。" },
      { text: "广谱（Broad Spectrum）标签很重要——只防 UVB 不防 UVA 的防晒霜是不够的。" },
      { text: "SPF15 阻挡约 93% UVB，SPF30 约 97%，SPF50 约 98%。从 30 到 50 只多了 1% 的防护力——但价格可能贵了一倍。" },
      { heading: "☀️ 重点整理", text: "✅ SPF30 广谱防护已经足够日常使用\n✅ 出门前 15 分钟擦，每 2 小时补擦一次\n✅ 物理防晒（氧化锌）对敏感肌更安全\n❌ 不是 SPF50 就比 SPF30 强很多——实际差距只有 1%\n❌ 阴天也要防晒——UVA 穿透云层\n❌ 不要只涂脸——耳朵、脖子、手背也要照顾到" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-059",
    title: "抗氧化全攻略：药师的实用小课堂",
    kicker: "Kris supplement notes",
    category: "Clinical",
    date: "20 May 2025",
    readTime: "3 min",
    excerpt: "抗氧化是护肤的核心——但很多人不知道从何开始。自由基是皮肤衰老的主要原因之一。",
    cover: "/products/fortress-plus-1.png",
    accent: "#6a5a8a",
    body: [
      { text: "抗氧化是护肤的核心——但很多人不知道从何开始。自由基是皮肤衰老的主要原因之一。" },
      { text: "但问题来了。" },
      { text: "防晒是最好的抗氧化——紫外线是最大的自由基来源。不防晒，抗氧化白做。" },
      { text: "维生素 C + 维生素 E 搭配使用效果更好——两者可以互相再生，1+1>2。" },
      { text: "多酚类（如绿茶萃取、白藜芦醇、虾青素）也是强大的抗氧化剂。" },
      { heading: "🛡️ 重点整理", text: "✅ 维 C + 维 E 搭配效果 1+1>2\n✅ 防晒是最好的抗氧化——最大的自由基来源是紫外线\n✅ 多种抗氧化剂搭配比单一更好\n❌ 不要只靠一种抗氧化剂——多种搭配更好\n❌ 不要忽略防晒——不防晒抗氧化白做" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-060",
    title: "关于维生素C护肤，药师想说的四件事",
    kicker: "Pharmacist explains",
    category: "Ingredient",
    date: "12 Mar 2025",
    readTime: "3 min",
    excerpt: "维生素 C 是最经典的抗氧化成分之一——但用错了方式，效果大打折扣。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#b07c2f",
    body: [
      { text: "维生素 C 是最经典的抗氧化成分之一——但用错了方式，效果大打折扣。" },
      { text: "也就是说——" },
      { text: "和烟酰胺可以一起使用——现代研究已推翻了早期「不能同时用」的说法。" },
      { text: "L-ascorbic acid 是最有效的形式——浓度 10–20% 最佳。pH 值需要在 3.5 以下才能有效渗透。" },
      { text: "维 C + 防晒 = 更强的防晒效果——维 C 可以帮助中和紫外线产生的自由基。" },
      { text: "产品应该是棕色或不透明包装——透明包装会让维 C 快速氧化。变黄说明已经失效。" },
      { heading: "🍊 重点整理", text: "✅ 早晨使用搭配防晒效果更好\n✅ L-ascorbic acid 浓度 10–20% 最佳\n✅ 选择棕色/不透明包装的产品\n❌ 不要买透明包装的维 C 精华——容易氧化\n❌ 变黄变棕色就不要用了——已经失效" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-061",
    title: "这个烟酰胺问题，太多人忽略了",
    kicker: "Pharmacist explains",
    category: "Ingredient",
    date: "27 Jan 2026",
    readTime: "3 min",
    excerpt: "你以为美白只能靠维 C？烟酰胺也很强——而且更温和，适合更多人。",
    cover: "/editorial/story-brightening.png",
    accent: "#a65a2f",
    body: [
      { text: "你以为美白只能靠维 C？烟酰胺也很强——而且更温和，适合更多人。" },
      { text: "有没有想过为什么？" },
      { text: "两者搭配使用可以双重美白——一个在源头抑制，一个在运输拦截。" },
      { text: "烟酰胺的美白机制和维 C 不同——它抑制黑色素从黑色素细胞转运到角质细胞。" },
      { text: "烟酰胺还可以帮助减少毛孔外观——通过调节皮脂分泌实现。" },
      { heading: "✨ 重点整理", text: "✅ 维 C + 烟酰胺是经典美白组合\n✅ 敏感肌也能用——从低浓度开始\n❌ 不要同时使用高浓度两者——可能刺激\n❌ 不要期望立竿见影——需要持续使用 4–8 周" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "💬 你还知道什么关于烟酰胺的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-062",
    title: "孕妇护肤：药师的实用小课堂",
    kicker: "Clinical notes",
    category: "Editorial",
    date: "15 Jun 2025",
    readTime: "3 min",
    excerpt: "怀孕期间有些护肤成分需要避免——你知道哪些吗？不确定的时候，先咨询产科医生。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "怀孕期间有些护肤成分需要避免——你知道哪些吗？不确定的时候，先咨询产科医生。" },
      { text: "先来看看研究怎么说。" },
      { text: "✅ 安全成分：烟酰胺、透明质酸、神经酰胺、维生素 C、物理防晒。" },
      { text: "❌ 维 A 酸/视黄醇——口服是明确致畸的，外用虽然全身吸收量小但建议避免。" },
      { text: "怀孕期间黄褐斑可能加重——荷尔蒙变化导致色素沉着增加。物理防晒更加重要。" },
      { heading: "🤰 重点整理", text: "✅ 烟酰胺、透明质酸、神经酰胺是安全的\n✅ 物理防晒（氧化锌）对孕妇安全\n✅ 维生素 C 精华也是安全的选择\n❌ 避免维 A 酸/视黄醇——口服明确致畸\n❌ 避免高浓度水杨酸——虽然外用风险低但建议避免" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-063",
    title: "成分党入门，正确打开方式在这里",
    kicker: "Kris supplement notes",
    category: "Clinical",
    date: "07 May 2025",
    readTime: "3 min",
    excerpt: "想看懂护肤品成分表其实不难——学会这几招就够了。不需要化学学位。",
    cover: "/editorial/hero.jpg",
    accent: "#a62f4f",
    body: [
      { text: "想看懂护肤品成分表其实不难——学会这几招就够了。不需要化学学位。" },
      { text: "先来个基础课。" },
      { text: "有些成分在很低浓度下就有效（如视黄醇 0.3%、烟酰胺 2%）——不是浓度越高越好。" },
      { text: "防腐剂后面的成分浓度通常很低——如果活性成分排在防腐剂后面，含量可能不够。" },
      { text: "成分表按浓度从高到低排列——前 5 个通常占了产品的 80% 以上。" },
      { heading: "📚 重点整理", text: "✅ 前 5 个成分决定产品的主要功效\n✅ 看成分比看品牌更重要\n✅ 学会识别常见的刺激成分\n❌ 不是浓度越高越好——要看具体成分\n❌ 不要被「含有 XX」骗了——要看排在第几位" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "有问题欢迎留言区讨论！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-064",
    title: "维生素B群，正确打开方式在这里",
    kicker: "Supplement truths",
    category: "Ingredient",
    date: "01 Sep 2025",
    readTime: "3 min",
    excerpt: "维生素 B 群不是「吃了尿会变黄」这么简单——它对皮肤和头发健康都很重要。",
    cover: "/products/fortress-plus-1.png",
    accent: "#2fa66b",
    body: [
      { text: "维生素 B 群不是「吃了尿会变黄」这么简单——它对皮肤和头发健康都很重要。" },
      { text: "有没有想过为什么？" },
      { text: "B7（生物素）对头发和指甲健康特别重要——缺 B7 会导致脱发和指甲脆弱。" },
      { text: "B 群参与能量代谢、神经功能和皮肤健康——是身体的「能量转换器」。" },
      { text: "压力大时 B 群消耗会增加——需要额外补充。素食者也需要特别注意 B12 的摄取。" },
      { heading: "💊 重点整理", text: "✅ 均衡饮食通常可以获取足够的 B 群\n✅ 压力大时可以考虑补充\n✅ 素食者需要特别关注 B12\n❌ 不要空腹吃高剂量 B 群——可能引起胃部不适\n❌ 尿液变黄是正常的——不代表吸收更好" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-065",
    title: "别再乱买护肤迷思产品了",
    kicker: "Kris notes",
    category: "Ingredient",
    date: "12 Jan 2026",
    readTime: "3 min",
    excerpt: "护肤迷思比你想的多——今天来破解几个最常见的。很多人花大钱买产品，却被迷思误导了。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#6a5a8a",
    body: [
      { text: "护肤迷思比你想的多——今天来破解几个最常见的。很多人花大钱买产品，却被迷思误导了。" },
      { text: "但问题来了。" },
      { text: "❌ 天然 = 安全——很多天然成分也有刺激性和毒性（如精油、花粉）。" },
      { text: "❌ 排毒面膜可以「排毒」——皮肤没有「排毒」功能，那是肝脏的工作。" },
      { text: "❌ 一天见效的产品——要么含违禁成分，要么是心理作用。" },
      { heading: "🤔 重点整理", text: "✅ 用科学的眼光看待护肤\n✅ 不要被夸张的广告语骗了\n✅ 选择有研究支持的成分\n❌ 不要相信「一天见效」的产品\n❌ 不要挤痘痘——会留下疤痕和色素沉着" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-066",
    title: "别再乱买敏感肌护理产品了",
    kicker: "Supplement truths",
    category: "Editorial",
    date: "14 Apr 2025",
    readTime: "3 min",
    excerpt: "敏感肌最重要的护肤原则：精简和温和。不是不能护肤，只是需要更聪明地选择。",
    cover: "/editorial/story-brightening.png",
    accent: "#b07c2f",
    body: [
      { text: "敏感肌最重要的护肤原则：精简和温和。不是不能护肤，只是需要更聪明地选择。" },
      { text: "先来看看研究怎么说。" },
      { text: "新产品先在耳后或手腕内侧试用 24–48 小时——确认没有反应再上脸。" },
      { text: "常见刺激成分：香精、酒精、高浓度酸类、精油、防腐剂。敏感肌需要避开这些。" },
      { text: "修复屏障的成分：神经酰胺、泛醇（B5）、积雪草、透明质酸——这些是敏感肌的好朋友。" },
      { heading: "🩹 重点整理", text: "✅ 精简产品——越少越好，给皮肤喘息的空间\n✅ 选择标注「fragrance-free」的产品\n✅ 新产品一定要先试用\n❌ 不要频繁更换产品——给皮肤适应的时间\n❌ 不要用过热的水洗脸——会破坏屏障" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-067",
    title: "这个男性护肤问题，太多人忽略了",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "12 Feb 2026",
    readTime: "3 min",
    excerpt: "男性护肤不需要很复杂——基础三步就足够。但很多男性觉得护肤「不够男子汉」。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#a65a2f",
    body: [
      { text: "男性护肤不需要很复杂——基础三步就足够。但很多男性觉得护肤「不够男子汉」。" },
      { text: "怎么说呢？" },
      { text: "防晒不是「女生才做的事」——它是预防皮肤癌最有效的方式。男性皮肤癌风险其实比女性更高。" },
      { text: "基础三步：温和洁面 + 保湿 + 防晒。3 分钟搞定。" },
      { text: "剃须后选择不含酒精的须后产品以减少刺激——酒精会让皮肤更干更敏感。" },
      { heading: "👨 重点整理", text: "✅ 洁面 + 保湿 + 防晒三步足够\n✅ 防晒是预防皮肤癌最有效的方式\n✅ 剃须后用温和的须后产品\n❌ 不要用肥皂洗脸——太刺激了\n❌ 不要忽视皮肤异常——及时看医生" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-068",
    title: "蛋白质摄入的二个冷知识",
    kicker: "Pharmacist explains",
    category: "Editorial",
    date: "01 Apr 2025",
    readTime: "3 min",
    excerpt: "蛋白质是肌肉修复和生长的基础——但很多亚洲人长期蛋白质摄取不足。",
    cover: "/editorial/hero.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "蛋白质是肌肉修复和生长的基础——但很多亚洲人长期蛋白质摄取不足。" },
      { text: "简单来说：" },
      { text: "优质来源：鸡蛋、鱼类、鸡肉、牛奶、豆制品。每餐都应该有足够的蛋白质。" },
      { text: "40 岁以后肌肉量每 10 年约减少 3–8%——这就是为什么中老年人更容易跌倒和骨折。" },
      { text: "老年人每天建议摄取约 1.0–1.2g 每公斤体重的蛋白质——比年轻人需要更多。" },
      { heading: "💪 重点整理", text: "✅ 每餐都应该有足够的蛋白质——均匀分布比一次性大量更好\n✅ 运动后 30–60 分钟内摄取效果最佳\n✅ 乳清蛋白是方便的补充方式\n❌ 不是只有健身才需要蛋白质\n❌ 不要只靠蛋白粉——天然食物更好" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-069",
    title: "先别急着买积雪草",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "21 Nov 2025",
    readTime: "3 min",
    excerpt: "CICA 产品为什么这么火？因为积雪草（Centella Asiatica）真的有用——在亚洲已经有悠久的使用历史。",
    cover: "/products/fortress-plus-1.png",
    accent: "#a62f4f",
    body: [
      { text: "CICA 产品为什么这么火？因为积雪草（Centella Asiatica）真的有用——在亚洲已经有悠久的使用历史。" },
      { text: "简单来说：" },
      { text: "积雪草可以帮助修复受损的皮肤屏障——对敏感肌和痘痘肌特别友好。" },
      { text: "CICA 产品适合用来做「皮肤急救」——晒后、过敏后都可以使用。" },
      { text: "积雪草含有积雪草苷和羟基积雪草苷等活性成分——帮助促进胶原蛋白合成、舒缓发炎。" },
      { heading: "🌿 重点整理", text: "✅ 舒缓 + 修复双重功效\n✅ 适合敏感肌和痘痘肌\n✅ 晒后急救的好选择\n❌ 不是所有 CICA 产品浓度都够\n❌ 单靠积雪草不能解决所有皮肤问题" },
      { heading: "药师小贴士 💊", text: "💊 每个人的体质不同，适合别人的不一定适合你。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-070",
    title: "一文读懂锌与皮肤",
    kicker: "Clinical notes",
    category: "Editorial",
    date: "13 Jul 2025",
    readTime: "3 min",
    excerpt: "痘痘一直好不了？也许你缺的不是祛痘产品，而是锌——一种常被忽略的矿物质。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#2fa66b",
    body: [
      { text: "痘痘一直好不了？也许你缺的不是祛痘产品，而是锌——一种常被忽略的矿物质。" },
      { text: "简单来说：" },
      { text: "富含锌的食物：牡蛎（锌含量最高）、红肉、南瓜子、鹰嘴豆、腰果。" },
      { text: "葡萄糖酸锌或吡啶甲酸锌的吸收率较好——不要空腹服用高剂量锌，会引起恶心。" },
      { text: "研究表明锌可以帮助减少痘痘的炎症、促进伤口愈合、调节皮脂分泌。" },
      { heading: "⚡ 重点整理", text: "✅ 缺锌的人更容易出现皮肤问题\n✅ 食补优先——牡蛎是锌的最佳来源\n✅ 搭配维生素 C 可以提高吸收\n❌ 不要长期高剂量补充——会干扰铜吸收\n❌ 不要以为痘痘只是表面问题——内部营养也很重要" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-071",
    title: "别再乱买Omega-3产品了",
    kicker: "Supplement truths",
    category: "Supplement",
    date: "25 Jan 2025",
    readTime: "3 min",
    excerpt: "鱼油不只是「保养心血管」——Omega-3 对皮肤、大脑和关节都有重要影响。",
    cover: "/editorial/story-brightening.png",
    accent: "#6a5a8a",
    body: [
      { text: "鱼油不只是「保养心血管」——Omega-3 对皮肤、大脑和关节都有重要影响。" },
      { text: "先来个基础课。" },
      { text: "Omega-3 对心血管健康、大脑功能和关节健康都有帮助——是「全身性」的营养素。" },
      { text: "好的鱼油不应该有很重的鱼腥味——有腥味可能已经氧化，氧化的鱼油反而有害。" },
      { text: "EPA 在抗炎方面可能比 DHA 更有效——对痘痘和湿疹的炎症有帮助。" },
      { heading: "🐟 重点整理", text: "✅ EPA 在抗炎方面更有效——痘痘/湿疹患者可以关注\n✅ 选择经过重金属检测和氧化检测的产品\n✅ 冷藏保存可以延缓氧化\n❌ 不是所有鱼油纯度都一样——看 EPA+DHA 含量\n❌ 有腥味的鱼油可能已经氧化——不建议服用" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-072",
    title: "别再乱买肠道健康产品了",
    kicker: "Supplement truths",
    category: "Supplement",
    date: "06 Jan 2026",
    readTime: "3 min",
    excerpt: "皮肤是肠道的下游——肠道健康直接影响皮肤状态。很多人花大钱买护肤品，却忽略了肠道。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#b07c2f",
    body: [
      { text: "皮肤是肠道的下游——肠道健康直接影响皮肤状态。很多人花大钱买护肤品，却忽略了肠道。" },
      { text: "也就是说——" },
      { text: "膳食纤维是肠道菌群的「食物」——不够的话有益菌会饿死。大多数人每天膳食纤维不到建议量的一半。" },
      { text: "肠道菌群失衡会导致全身性炎症——皮肤是受害者之一。痘痘、湿疹、暗沉都可能和肠道有关。" },
      { text: "发酵食物（酸奶、泡菜、味噌）是天然的益生菌来源——比补充剂更便宜也更自然。" },
      { heading: "🦠 重点整理", text: "✅ 每天摄取足够的膳食纤维——蔬菜、水果、全谷物\n✅ 发酵食物是天然的益生菌来源\n✅ 多喝水——帮助膳食纤维发挥作用\n❌ 不要过度使用抗菌产品——会破坏菌群\n❌ 不要忽视肠道不适——可能是菌群失衡的信号" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-073",
    title: "你真的了解祛痘全攻略吗？",
    kicker: "Supplement truths",
    category: "Supplement",
    date: "13 Apr 2025",
    readTime: "3 min",
    excerpt: "痘痘的成因很复杂——荷尔蒙、细菌、炎症、饮食都可能是因素。治疗需要耐心，通常需要 6–8 周。",
    cover: "/editorial/hero.jpg",
    accent: "#a65a2f",
    body: [
      { text: "痘痘的成因很复杂——荷尔蒙、细菌、炎症、饮食都可能是因素。治疗需要耐心，通常需要 6–8 周。" },
      { text: "但问题来了。" },
      { text: "痘痘治疗的核心是「控制」而不是「根治」——需要长期管理。" },
      { text: "外用 A 醇可以帮助预防毛孔堵塞——但需要建立耐受。" },
      { text: "水杨酸（BHA）适合黑头和粉刺——脂溶性可以深入毛孔。" },
      { heading: "💪 重点整理", text: "✅ 找出痘痘的成因才能对症下药\n✅ 给产品足够的时间——6–8 周\n✅ 保持耐心——痘痘治疗是一场马拉松\n❌ 不要挤痘痘——会留下疤痕和色素沉着\n❌ 不要过度清洁——会加重炎症" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-074",
    title: "一文读懂维生素D",
    kicker: "Kris supplement notes",
    category: "Editorial",
    date: "02 Nov 2025",
    readTime: "3 min",
    excerpt: "很多人以为马来西亚天天有太阳，就不会缺 Vitamin D。其实刚好相反——我们反而比温带国家的人更容易缺乏。",
    cover: "/products/fortress-plus-1.png",
    accent: "#2f6a7d",
    body: [
      { text: "很多人以为马来西亚天天有太阳，就不会缺 Vitamin D。其实刚好相反——我们反而比温带国家的人更容易缺乏。" },
      { text: "先来看看研究怎么说。" },
      { text: "Vitamin D 不只是帮助钙吸收。它在免疫调节、情绪稳定、肌肉功能方面都扮演重要角色。缺 D 的人更容易疲倦、情绪低落。" },
      { text: "大多数人很难单靠食物获取足够的 Vitamin D。100g 三文鱼只有约 526 IU，而每天建议摄取量是 400–800 IU。" },
      { text: "Vitamin D 进入身体后，需要经过肝脏、肾脏转化，最后变成活性的 calcitriol。它会和细胞里的 VDR 结合，再向细胞发出讯号——影响超过 200 个基因的表达。" },
      { text: "SEANUTS 全国调查显示，约 47.5% 的 4–12 岁儿童 Vitamin D 水平不足。吉隆坡一项针对小学生的研究更发现：35.3% Vitamin D 缺乏、37.1% 不足。" },
      { heading: "☀️ 重点整理", text: "✅ 适量户外活动，让皮肤接触阳光——每天 15–20 分钟\n✅ 多摄取富含 Vitamin D 的食物——三文鱼、沙丁鱼、鸡蛋黄、强化牛奶\n✅ 如果很少晒太阳，考虑补充 Vitamin D3（胆钙化醇）\n❌ 不要以为吃多就补多——Vitamin D 是脂溶性的，过量会积累在体内\n❌ 不要只靠防晒霜——SPF 再高也不能替代阳光合成 Vitamin D" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-075",
    title: "压力管理的真相，和你想的不一样",
    kicker: "Kris supplement notes",
    category: "Ingredient",
    date: "15 Jan 2025",
    readTime: "3 min",
    excerpt: "压力会直接反映在你的皮肤上。不是比喻，是科学——皮质醇是皮肤的「隐形敌人」。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#a62f4f",
    body: [
      { text: "压力会直接反映在你的皮肤上。不是比喻，是科学——皮质醇是皮肤的「隐形敌人」。" },
      { text: "有没有想过为什么？" },
      { text: "长期压力还会导致毛囊提前进入休止期——这就是为什么压力大的时候掉头发特别多。" },
      { text: "压力触发皮质醇释放——导致痘痘爆发、湿疹发作、加速衰老和脱发。" },
      { text: "管理压力的方法：规律运动、冥想、深呼吸、充足睡眠、社交支持。" },
      { heading: "😰 重点整理", text: "✅ 规律运动是最好的压力管理工具——每天 30 分钟\n✅ 充足睡眠是压力管理的基础\n✅ 冥想和深呼吸可以快速降低皮质醇\n❌ 不要指望护肤品来抵消压力的伤害\n❌ 不要忽视持续的压力——它会影响全身健康" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-076",
    title: "别再乱买睡眠与皮肤产品了",
    kicker: "Supplement truths",
    category: "Clinical",
    date: "20 Apr 2025",
    readTime: "3 min",
    excerpt: "睡眠是最好的免费护肤品。这不是鸡汤，是科学——你熬的每一个夜，都在你的脸上记账。",
    cover: "/editorial/story-brightening.png",
    accent: "#2fa66b",
    body: [
      { text: "睡眠是最好的免费护肤品。这不是鸡汤，是科学——你熬的每一个夜，都在你的脸上记账。" },
      { text: "也就是说——" },
      { text: "睡眠不足会导致皮质醇升高——引发炎症、痘痘爆发和加速衰老。" },
      { text: "长期睡眠不足还会导致黑眼圈加重、肤色暗沉、免疫力下降——影响远不止皮肤。" },
      { text: "最佳睡眠时间是 7–8 小时——不是「睡够就行」，质量也很重要。" },
      { heading: "😴 重点整理", text: "✅ 每天 7–8 小时高质量睡眠\n✅ 睡前 1 小时避免屏幕蓝光\n✅ 保持规律的睡眠时间——比「睡够 8 小时」更重要\n❌ 不要熬夜后指望护肤品来补救——治标不治本\n❌ 下午 2 点后尽量避免咖啡因" },
      { text: "睡眠期间身体会进行细胞修复、胶原蛋白重建和炎症调节——这是护肤品做不到的「内部修复」。" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "💬 你还知道什么关于睡眠与皮肤的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-077",
    title: "热带气候护肤，正确打开方式在这里",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "17 Mar 2025",
    readTime: "3 min",
    excerpt: "在马来西亚这样的热带气候，护肤需要做一些调整——高温高湿不代表不需要保湿。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#6a5a8a",
    body: [
      { text: "在马来西亚这样的热带气候，护肤需要做一些调整——高温高湿不代表不需要保湿。" },
      { text: "怎么说呢？" },
      { text: "防晒选择防水耐汗的配方——SPF30+ 广谱防护足够日常使用。" },
      { text: "室内空调环境反而可能让皮肤变干——需要注意保湿。" },
      { text: "质地选择轻薄的凝胶或乳液——厚重面霜在热带气候容易闷痘。" },
      { heading: "🌴 重点整理", text: "✅ 轻薄质地更适合热带气候\n✅ 防水耐汗的防晒配方\n✅ 空调房内需要额外保湿\n❌ 不要因为出汗就忽略保湿\n❌ 不要过度清洁——出汗后温和清洁就好" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-078",
    title: "视黄醇的真相，和你想的不一样",
    kicker: "Kris supplement notes",
    category: "Clinical",
    date: "24 Jun 2025",
    readTime: "3 min",
    excerpt: "A 醇入门的「翻车」经历，几乎每个人都经历过。脱皮、泛红、干燥——其实这些都是可以避免的。",
    cover: "/editorial/hero.jpg",
    accent: "#b07c2f",
    body: [
      { text: "A 醇入门的「翻车」经历，几乎每个人都经历过。脱皮、泛红、干燥——其实这些都是可以避免的。" },
      { text: "简单来说：" },
      { text: "不是每个人都需要 A 醇——如果你的皮肤已经很好，维持现状就好。" },
      { text: "三明治法：先涂保湿→A 醇→再涂保湿——可以大幅减少刺激。" },
      { text: "「皮肤转换期」是正常的——通常在开始使用的前 2–4 周出现。不是过敏，是皮肤在适应。" },
      { heading: "🌙 重点整理", text: "✅ 三明治法可以减少刺激\n✅ 给皮肤足够的适应时间\n❌ 不要频繁使用——一周 2–3 次足够\n❌ 不要和其他强效活性成分叠加" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-079",
    title: "关于化妆品安全，这些误区你踩了几个？",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "22 Feb 2026",
    readTime: "3 min",
    excerpt: "化妆品过期后使用可能导致细菌滋生和皮肤过敏——但很多人不知道怎么判断是否过期。",
    cover: "/products/fortress-plus-1.png",
    accent: "#a65a2f",
    body: [
      { text: "化妆品过期后使用可能导致细菌滋生和皮肤过敏——但很多人不知道怎么判断是否过期。" },
      { text: "简单来说：" },
      { text: "存放环境很重要——高温高湿会加速变质。不要放在浴室或车内暴晒。" },
      { text: "如果产品出现异味、变色、质地改变——即使没到保质期也应该丢弃。" },
      { text: "PAO 符号（如 12M）表示开封后 12 个月内使用完。没有 PAO 的产品建议开封后 12 个月内用完。" },
      { heading: "💄 重点整理", text: "✅ 定期清理化妆包——每 3 个月检查一次\n✅ 存放在阴凉干燥处\n✅ 用小勺取用罐装产品——避免手指污染\n❌ 不要放在浴室——高温高湿加速变质\n❌ 不要用手直接挖罐装产品" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-080",
    title: "先别急着买保湿真相",
    kicker: "Pharmacist explains",
    category: "Supplement",
    date: "16 Mar 2025",
    readTime: "3 min",
    excerpt: "保湿不是「涂一层 cream 就好」——关键是选对成分。油性皮肤也需要保湿。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#2f6a7d",
    body: [
      { text: "保湿不是「涂一层 cream 就好」——关键是选对成分。油性皮肤也需要保湿。" },
      { text: "有没有想过为什么？" },
      { text: "透明质酸是保湿剂——需要搭配封闭剂才能锁住水分。单独用可能在干燥环境下反而吸走水分。" },
      { text: "保湿成分分三类：保湿剂（吸水，如透明质酸）、润肤剂（软化，如神经酰胺）、封闭剂（锁水，如凡士林）。" },
      { text: "神经酰胺是润肤剂——帮助修复皮肤屏障，是敏感肌的首选。" },
      { heading: "💧 重点整理", text: "✅ 保湿剂 + 封闭剂搭配效果最好\n✅ 油性皮肤选轻薄的凝胶或乳液\n✅ 干燥环境需要更强的封闭剂\n❌ 不是所有保湿产品都适合你的肤质\n❌ 不要只用透明质酸——需要封闭剂锁水" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-081",
    title: "先别急着买关节保健",
    kicker: "Supplement truths",
    category: "Clinical",
    date: "12 Sep 2025",
    readTime: "3 min",
    excerpt: "很多人关节痛就开始吃关节保健品。但你有没有想过：关节到底是什么？你补的成分真的对症吗？",
    cover: "/editorial/story-brightening.png",
    accent: "#a62f4f",
    body: [
      { text: "很多人关节痛就开始吃关节保健品。但你有没有想过：关节到底是什么？你补的成分真的对症吗？" },
      { text: "有没有想过为什么？" },
      { text: "K2 的作用是「引钙入骨」——没有 K2，补再多钙可能都白费。钙会沉积在血管里而不是骨骼中。" },
      { text: "Osteoliv 蕴含四大核心成分：活性胶原蛋白肽、海藻钙、维生素 D3、维生素 K2。四者协同作用，从不同层面支持关节健康。" },
      { text: "关节就像一部汽车。软骨是缓冲垫，滑液是润滑油。你不能只换一个零件——需要全面保养。" },
      { heading: "🦴 重点整理", text: "✅ 关节一开始觉得沙沙/卡卡的时候就要开始保健了——预防比治疗便宜\n✅ 2 型胶原蛋白的效果是 Glucosamine 的 2 倍——选对成分\n✅ K2 + D3 + 钙是黄金组合\n❌ 不要等痛到不行才来补——软骨磨损是不可逆的\n❌ 不要只看品牌广告，要看具体成分和剂量" },
      { text: "Glucosamine 研究显示约 50% 的人服用后没有明显效果——选对成分很重要。" },
      { heading: "药师小贴士 💊", text: "💊 药师小贴士：有任何疑问，先咨询专业药师或医生。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoGard——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-082",
    title: "玫瑰痤疮：你真的补对了吗？",
    kicker: "Kris notes",
    category: "Supplement",
    date: "09 Feb 2025",
    readTime: "3 min",
    excerpt: "玫瑰痤疮（Rosacea）不是「皮肤敏感」这么简单——它是一种血管性皮肤问题，需要正确对待。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#2fa66b",
    body: [
      { text: "玫瑰痤疮（Rosacea）不是「皮肤敏感」这么简单——它是一种血管性皮肤问题，需要正确对待。" },
      { text: "先来看看研究怎么说。" },
      { text: "壬二酸是玫瑰痤疮的常用外用成分——可以帮助减少炎症和泛红。" },
      { text: "触发因素：热食、辛辣食物、酒精、日晒、压力、极端温度。每个人的触发因素可能不同。" },
      { text: "主要表现为面部中央持续性泛红、可见血管丝、偶尔出现丘疹——容易和痘痘混淆。" },
      { heading: "🌹 重点整理", text: "✅ 使用温和无香料的产品——越简单越好\n✅ 选择矿物防晒（氧化锌）——化学防晒可能刺激\n✅ 记录触发因素日记——了解自己的「地雷」\n❌ 避免含酒精、薄荷、桉树油的产品\n❌ 严重时需要看皮肤科医生——不要自己乱搞" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-083",
    title: "防晒，正确打开方式在这里",
    kicker: "Kris supplement notes",
    category: "Editorial",
    date: "28 May 2025",
    readTime: "3 min",
    excerpt: "你以为涂了防晒就万事大吉了？其实大部分人防晒用量都不够——SPF50 可能只有 SPF10 的效果。",
    cover: "/editorial/hero.jpg",
    accent: "#6a5a8a",
    body: [
      { text: "你以为涂了防晒就万事大吉了？其实大部分人防晒用量都不够——SPF50 可能只有 SPF10 的效果。" },
      { text: "怎么说呢？" },
      { text: "出汗、游泳、擦脸都会降低防晒效果——防水配方也只能维持 40–80 分钟。" },
      { text: "SPF 测试是基于每平方厘米 2mg 的用量——用量不够的话，SPF50 实际上只有 SPF10–15 的防护力。" },
      { text: "脸部需要约 1/4 茶匙（约 1.2ml）——大约两个手指的长度。大部分人只涂了标准量的 1/4 到 1/2。" },
      { heading: "☀️ 重点整理", text: "✅ 脸部：两个手指长度的量\n✅ 每 2 小时补擦，出汗/游泳后立即补擦\n❌ 不要只擦薄薄一层——用量不够等于没擦\n❌ 不要忘记耳朵、脖子和手背" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "有问题欢迎留言区讨论！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-084",
    title: "别再乱买面膜产品了",
    kicker: "Clinical notes",
    category: "Ingredient",
    date: "15 Apr 2025",
    readTime: "3 min",
    excerpt: "面膜不是敷越久越好——10–15 分钟就够了。敷太久反而会倒吸皮肤水分。",
    cover: "/products/fortress-plus-1.png",
    accent: "#b07c2f",
    body: [
      { text: "面膜不是敷越久越好——10–15 分钟就够了。敷太久反而会倒吸皮肤水分。" },
      { text: "有没有想过为什么？" },
      { text: "面膜是锦上添花，不是急救神器——日常护肤才是基础。" },
      { text: "面膜的主要功能是封闭性补水——让精华成分在短时间内更好地渗透。" },
      { text: "敷太久面膜纸会变干，开始倒吸皮肤水分——得不偿失。" },
      { heading: "🧖 重点整理", text: "✅ 10–15 分钟就够了——不要敷到面膜纸干掉\n✅ 敏感肌选成分简单的——越少越好\n✅ 敷完后涂抹保湿产品锁住水分\n❌ 不要敷着面膜睡觉——会倒吸水分\n❌ 不要天天敷——过度水合反而伤皮肤" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "大家只有学会了，才不会交智商税。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Mist——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-085",
    title: "先别急着买湿疹",
    kicker: "Supplement truths",
    category: "Supplement",
    date: "24 Sep 2025",
    readTime: "3 min",
    excerpt: "湿疹不是「皮肤干燥」这么简单。它是一种屏障疾病——皮肤的「城墙」出了问题。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#a65a2f",
    body: [
      { text: "湿疹不是「皮肤干燥」这么简单。它是一种屏障疾病——皮肤的「城墙」出了问题。" },
      { text: "怎么说呢？" },
      { text: "Epsilon Ultra Soothing Cream 以 3:1:1 的生理比例输送神经酰胺 NP、AP 和 EOP——修复屏障，不是「止痒」。" },
      { text: "问题产品三大特征：全部天然却立马见效、一个 cream 解决所有问题、一停用就反弹。" },
      { text: "网路神 cream 又爆雷了。12 岁男童连续涂抹两个月后体重暴增六公斤——含强效类固醇的产品短期见效但长期伤害巨大。" },
      { heading: "🛡️ 重点整理", text: "✅ 湿疹的治疗核心是修复屏障，不是「止痒」\n✅ 神经酰胺 3:1:1 比例是关键——选对产品\n✅ 棉质衣物比合成纤维更适合湿疹患者\n❌ 不要用含类固醇的「神cream」——短期见效但长期伤害\n❌ 不要听网红说「全天然无副作用」——天然不等于安全\n❌ 不要抓挠——会加重炎症和感染风险" },
      { text: "湿疹皮肤流失约三倍于健康皮肤的水分——形成痒→抓→发作的恶性循环。" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "💬 你还知道什么关于湿疹的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-086",
    title: "益生菌的真相，和你想的不一样",
    kicker: "Pharmacist explains",
    category: "Editorial",
    date: "11 Feb 2025",
    readTime: "3 min",
    excerpt: "皮肤是肠道的下游。这句话不是鸡汤，是科学——很多皮肤问题可能要从肠道开始解决。",
    cover: "/editorial/story-brightening.png",
    accent: "#2f6a7d",
    body: [
      { text: "皮肤是肠道的下游。这句话不是鸡汤，是科学——很多皮肤问题可能要从肠道开始解决。" },
      { text: "先来个基础课。" },
      { text: "肠脑皮肤轴——肠道炎症、营养状况和微生物组平衡会直接反映在皮肤上。肠道菌群失衡可能导致全身性炎症。" },
      { text: "膳食纤维是肠道菌群的「食物」——不够的话有益菌会饿死。大多数人每天膳食纤维摄取量不到建议的一半。" },
      { text: "NUCA® RevoBiotic 将益生元、益生菌、后生元、消化酶合并在一包中——三者协同比单一成分更有效。" },
      { heading: "🦠 重点整理", text: "✅ 益生菌 + 益生元 + 后生元三者搭配效果最好\n✅ 皮肤问题反复发作，也许该看看肠道\n✅ 发酵食物（酸奶、泡菜、味噌）是天然的益生菌来源\n❌ 不是所有益生菌菌株都一样——要看具体研究支持的菌株\n❌ 不要指望一包益生菌就解决所有问题——需要持续摄取" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "好的配方，自己会说话。" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-087",
    title: "搞懂水杨酸，别再交智商税",
    kicker: "Pharmacist explains",
    category: "Ingredient",
    date: "14 Jul 2025",
    readTime: "3 min",
    excerpt: "水杨酸（Salicylic Acid / BHA）是油痘肌的救星——但用错方式反而会刺激皮肤。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#a62f4f",
    body: [
      { text: "水杨酸（Salicylic Acid / BHA）是油痘肌的救星——但用错方式反而会刺激皮肤。" },
      { text: "先来看看研究怎么说。" },
      { text: "水杨酸最初来自柳树皮——天然来源，但现在通过合成可以获得更纯更稳定的版本。" },
      { text: "一般建议浓度 0.5–2%，从低浓度开始。油痘肌可以每天使用，干性或敏感肌建议每周 2–3 次。" },
      { text: "水杨酸是脂溶性的——可以深入毛孔内部溶解堵塞的油脂和老废角质。这是它比果酸更适合油痘肌的原因。" },
      { heading: "🧪 重点整理", text: "✅ 脂溶性——能深入毛孔清洁\n✅ 油痘肌的好朋友——黑头粉刺的克星\n✅ 低浓度（0.5%）就可以有效果\n❌ 不要和高浓度果酸同时使用——会过度去角质\n❌ 敏感肌要从低浓度开始，每周 1–2 次" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-088",
    title: "神经酰胺的真相，和你想的不一样",
    kicker: "Clinical notes",
    category: "Supplement",
    date: "04 Apr 2025",
    readTime: "3 min",
    excerpt: "神经酰胺（Ceramide）是皮肤屏障的核心成分——少了它，皮肤就像没关门的房子，水分一直流失。",
    cover: "/editorial/hero.jpg",
    accent: "#2fa66b",
    body: [
      { text: "神经酰胺（Ceramide）是皮肤屏障的核心成分——少了它，皮肤就像没关门的房子，水分一直流失。" },
      { text: "简单来说：" },
      { text: "神经酰胺占皮肤屏障脂质约 50%——是「城墙」的主要建筑材料。" },
      { text: "3:1:1 比例是健康角质层的精确脂质比例——不是随便加一点神经酰胺就有用。" },
      { text: "Epsilon Ultra Soothing Cream 就是用这个比例来修复屏障的——神经酰胺 NP、AP 和 EOP。" },
      { text: "屏障受损会导致经皮水分流失（TEWL）增加——皮肤越干→屏障越差→越干的恶性循环。" },
      { heading: "🧬 重点整理", text: "✅ 3:1:1 比例是关键——不是所有产品都对\n✅ 修复屏障是敏感肌和湿疹的第一步\n✅ 搭配透明质酸效果更好——一个锁水一个补水\n❌ 不是所有含神经酰胺的产品比例都对\n❌ 不要只看「含有神经酰胺」——要看排在成分表第几位" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "觉得有用的话，分享给身边需要的朋友吧～" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-089",
    title: "关于糖与皮肤老化，药师想说的七件事",
    kicker: "Pharmacist explains",
    category: "Ingredient",
    date: "08 Nov 2025",
    readTime: "3 min",
    excerpt: "你喝的那杯奶茶，可能正在让你的脸加速老化——糖是皮肤的隐形杀手。",
    cover: "/products/fortress-plus-1.png",
    accent: "#6a5a8a",
    body: [
      { text: "你喝的那杯奶茶，可能正在让你的脸加速老化——糖是皮肤的隐形杀手。" },
      { text: "简单来说：" },
      { text: "过量糖摄入会导致糖化反应（glycation）——糖分子附着在胶原蛋白上使其变硬变脆，失去弹性。" },
      { text: "WHO 建议每天添加糖摄入不超过 25g——一杯奶茶就可能超标。" },
      { text: "高糖饮食引发胰岛素飙升，进而刺激皮脂分泌和炎症反应——痘痘的元凶之一。" },
      { heading: "🍬 重点整理", text: "✅ 用水果代替甜食——天然糖分有纤维缓冲\n✅ 看营养标签——隐藏的糖分很多（酱料、饮料、面包）\n✅ 选择低 GI 食物——血糖稳定对皮肤更好\n❌ 不是说完全不能吃糖——适量就好\n❌ 不要被「无糖」标签骗了——可能只是没加蔗糖" },
      { heading: "药师小贴士 💊", text: "💊 每个人的体质不同，适合别人的不一定适合你。" },
      { text: "你有试过糖与皮肤老化相关的产品吗？我想听听你的分享。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-090",
    title: "这个维生素D问题，太多人忽略了",
    kicker: "Kris supplement notes",
    category: "Ingredient",
    date: "21 Dec 2025",
    readTime: "3 min",
    excerpt: "你有没有注意到，冬天特别容易感冒、疲倦、情绪低落？可能跟 Vitamin D 有关。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#b07c2f",
    body: [
      { text: "你有没有注意到，冬天特别容易感冒、疲倦、情绪低落？可能跟 Vitamin D 有关。" },
      { text: "先来看看研究怎么说。" },
      { text: "研究显示 Vitamin D 不足与呼吸道感染风险增加有关——补充 Vitamin D 可以降低上呼吸道感染的几率。" },
      { text: "冬天阳光角度低，UVB 无法有效到达地面，皮肤合成 Vitamin D 的效率大幅下降。" },
      { text: "Vitamin D 的「窗口期」：从 11 月到 3 月，大部分地区几乎无法通过阳光合成足够的 Vitamin D。" },
      { heading: "☀️ 重点整理", text: "✅ 冬天特别需要关注 Vitamin D 摄取\n✅ 补充 Vitamin D3 是最有效的方式\n❌ 不要等症状严重才来补——预防性补充更重要\n❌ 不要只在冬天补——全年都需要" },
      { heading: "药师小贴士 💊", text: "💊 记住：保健品不是药物，有症状请先就医。" },
      { text: "💬 你还知道什么关于维生素D的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-091",
    title: "这个湿疹问题，太多人忽略了",
    kicker: "Kris supplement notes",
    category: "Editorial",
    date: "30 Dec 2025",
    readTime: "3 min",
    excerpt: "你有没有发现，压力大的时候湿疹特别容易发作？这不是巧合——肠脑皮肤轴在作怪。",
    cover: "/editorial/story-brightening.png",
    accent: "#a65a2f",
    body: [
      { text: "你有没有发现，压力大的时候湿疹特别容易发作？这不是巧合——肠脑皮肤轴在作怪。" },
      { text: "怎么说呢？" },
      { text: "压力会触发皮质醇释放——皮质醇升高会抑制免疫系统，导致湿疹发作。" },
      { text: "环境因素（尘螨、宠物毛发、花粉）也是常见的触发因素——需要逐一排查。" },
      { text: "湿疹的管理需要长期坚持——保湿是基础，每天至少 2 次。" },
      { heading: "🛡️ 重点整理", text: "✅ 每天至少保湿 2 次——沐浴后立即涂抹效果最好\n✅ 记录发作日记——找出你的触发因素\n❌ 不要自行使用类固醇药膏——需要医生指导\n❌ 不要忽视压力管理——它直接影响皮肤" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "好的配方，自己会说话。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-092",
    title: "辅酶Q10，正确打开方式在这里",
    kicker: "Kris supplement notes",
    category: "Supplement",
    date: "07 Jul 2025",
    readTime: "3 min",
    excerpt: "辅酶 Q10（CoQ10）是细胞能量工厂的核心成分——随着年龄增长，身体合成它的能力会下降。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "辅酶 Q10（CoQ10）是细胞能量工厂的核心成分——随着年龄增长，身体合成它的能力会下降。" },
      { text: "简单来说：" },
      { text: "它也是一种强大的抗氧化剂——可以帮助保护细胞免受自由基伤害。" },
      { text: "CoQ10 参与细胞能量产生——线粒体的「燃料」。没有它，细胞就没有能量。" },
      { text: "对心血管健康也有潜在好处——心脏是 CoQ10 需求量最高的器官。" },
      { heading: "❤️ 重点整理", text: "✅ CoQ10 对心脏和皮肤都有帮助\n✅ 30 岁以后合成能力下降——可能需要补充\n✅ 泛醇（Ubiquinol）比泛醌（Ubiquinone）吸收率更好\n❌ 不要和抗凝血药物同时使用——先咨询医生\n❌ 吸收率因配方而异——选择经过验证的产品" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-093",
    title: "乳制品与痘痘，正确打开方式在这里",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "15 Sep 2025",
    readTime: "3 min",
    excerpt: "如果你痘痘一直反反复复，也许该试试减少乳制品——很多人不知道这两者的关联。",
    cover: "/editorial/hero.jpg",
    accent: "#a62f4f",
    body: [
      { text: "如果你痘痘一直反反复复，也许该试试减少乳制品——很多人不知道这两者的关联。" },
      { text: "也就是说——" },
      { text: "酸奶和发酵乳制品的影响可能较小——发酵过程分解了部分 IGF-1。" },
      { text: "牛奶中的 IGF-1（类胰岛素生长因子）可以刺激皮脂分泌——痘痘形成的关键环节。" },
      { text: "脱脂牛奶的影响可能比全脂更大——加工过程改变了蛋白质结构，IGF-1 含量反而更高。" },
      { heading: "🥛 重点整理", text: "✅ 可以试试减少或排除乳制品 2–4 周观察变化\n✅ 酸奶是相对安全的替代——发酵过程改变了牛奶蛋白\n❌ 不是说所有人都要戒牛奶——观察自己的身体反应\n❌ 不要盲目跟风——每个人的情况不同" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "💬 你还知道什么关于乳制品与痘痘的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-094",
    title: "姜黄的真相，和你想的不一样",
    kicker: "Clinical notes",
    category: "Clinical",
    date: "28 Mar 2025",
    readTime: "3 min",
    excerpt: "姜黄不只是咖喱里的香料——它是一种强大的抗炎成分。但有一个问题：单独服用吸收率很低。",
    cover: "/products/fortress-plus-1.png",
    accent: "#2fa66b",
    body: [
      { text: "姜黄不只是咖喱里的香料——它是一种强大的抗炎成分。但有一个问题：单独服用吸收率很低。" },
      { text: "简单来说：" },
      { text: "研究表明姜黄对关节炎、消化问题和全身性炎症都有潜在帮助。" },
      { text: "Osteoliv 中就含有姜黄素——搭配其他成分协同作用。" },
      { text: "Curcumin（姜黄素）需要搭配黑胡椒中的胡椒碱才能显著提高吸收——可以提高 2000%。" },
      { heading: "🟡 重点整理", text: "✅ 搭配黑胡椒吸收率提高 2000%\n✅ 抗炎 + 抗氧化双重功效\n✅ 对关节和消化都有帮助\n❌ 不要单独服用姜黄粉——吸收率很低\n❌ 姜黄会让衣服和台面染色——小心使用" },
      { heading: "药师小贴士 💊", text: "💊 不要追求速效，皮肤和身体的改善需要时间。" },
      { text: "💬 你还知道什么关于姜黄的迷思吗？欢迎留言区分享！" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoGard——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-095",
    title: "关于色素沉着，这些误区你踩了几个？",
    kicker: "Kris notes",
    category: "Ingredient",
    date: "23 Mar 2025",
    readTime: "3 min",
    excerpt: "防晒是所有色素治疗的基础——没有防晒，其他治疗效果都打折扣。但很多人忽略这一点。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#6a5a8a",
    body: [
      { text: "防晒是所有色素治疗的基础——没有防晒，其他治疗效果都打折扣。但很多人忽略这一点。" },
      { text: "怎么说呢？" },
      { text: "传明酸适合黄褐斑——通过抑制纤溶酶原激活来减少色素。" },
      { text: "外用成分：维生素 C（抗氧化+美白）、烟酰胺（抑制转运）、壬二酸（抑制酪氨酸酶）。" },
      { text: "如果外用效果不明显，化学焕肤或激光可以考虑——但术后护理很重要。" },
      { text: "色素淡化需要时间——至少 3–6 个月才能看到明显变化。不要指望一周见效。" },
      { heading: "✨ 重点整理", text: "✅ 防晒是所有色素治疗的基础——不防晒其他都白做\n✅ 维 C + 烟酰胺 + 壬二酸是经典组合\n✅ 给皮肤足够的时间——3–6 个月\n❌ 不要指望一周见效——色素淡化需要耐心\n❌ 不要忽略防晒——紫外线会加重色素沉着" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "记住：不是越贵越好，也不是天然就安全。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-096",
    title: "为什么你的烟酰胺一直没效？",
    kicker: "Pharmacist explains",
    category: "Supplement",
    date: "07 Jan 2025",
    readTime: "3 min",
    excerpt: "烟酰胺（Niacinamide）是维生素 B3 的衍生物，一个超全能的护肤成分——但很多人用错了浓度。",
    cover: "/editorial/story-brightening.png",
    accent: "#b07c2f",
    body: [
      { text: "烟酰胺（Niacinamide）是维生素 B3 的衍生物，一个超全能的护肤成分——但很多人用错了浓度。" },
      { text: "也就是说——" },
      { text: "烟酰胺可以帮助控制皮脂分泌、缩小毛孔外观、强化皮肤屏障、改善色素沉着——几乎什么都能做。" },
      { text: "和维生素 C 可以一起使用——现代研究已经推翻了早期「不能同时用」的说法。" },
      { text: "建议浓度在 2–5% 之间——10% 反而可能引起刺激和泛红。不是浓度越高越好。" },
      { heading: "✨ 重点整理", text: "✅ 适合几乎所有肤质，包括敏感肌\n✅ 2–5% 浓度就可以看到效果\n✅ 早晚都可以使用——温和不刺激\n❌ 不是浓度越高越好——10% 可能反而刺激\n❌ 不要和高浓度酸类同时叠加——可能增加刺激风险" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-097",
    title: "玻尿酸：药师的实用小课堂",
    kicker: "Kris notes",
    category: "Ingredient",
    date: "31 Jan 2026",
    readTime: "3 min",
    excerpt: "玻尿酸可以吸收自身重量 1000 倍的水分——但用错方式反而会吸走皮肤的水分。",
    cover: "/editorial/story-epsilon.jpg",
    accent: "#a65a2f",
    body: [
      { text: "玻尿酸可以吸收自身重量 1000 倍的水分——但用错方式反而会吸走皮肤的水分。" },
      { text: "先来个基础课。" },
      { text: "在干燥环境下单独使用玻尿酸可能反而吸走皮肤水分——需要搭配封闭剂。" },
      { text: "皮肤中的玻尿酸可以帮助维持含水量，让皮肤看起来饱满有弹性。但随着年龄增长，合成能力会下降。" },
      { text: "口服玻尿酸研究显示对皮肤水分和关节健康都有帮助——不只是外用有效。" },
      { heading: "💧 重点整理", text: "✅ 外用要搭配封闭剂（如面霜）锁住水分\n✅ 口服玻尿酸研究支持对皮肤和关节有益\n✅ 分子量越小渗透越深——但不一定越好\n❌ 干燥环境下单独用玻尿酸可能反而吸走水分\n❌ 不是所有玻尿酸产品浓度都够" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "好的配方，自己会说话。" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-098",
    title: "别再乱买益生菌产品了",
    kicker: "Kris notes",
    category: "Clinical",
    date: "30 Dec 2025",
    readTime: "3 min",
    excerpt: "很多人以为益生菌只是「帮助消化」。其实它的影响力远超你的想象——从免疫到情绪到皮肤。",
    cover: "/editorial/hero.jpg",
    accent: "#2f6a7d",
    body: [
      { text: "很多人以为益生菌只是「帮助消化」。其实它的影响力远超你的想象——从免疫到情绪到皮肤。" },
      { text: "先来个基础课。" },
      { text: "肠道菌群的数量超过人体细胞的总数——它们不是「寄生虫」，而是共生伙伴。" },
      { text: "Fortress 里的益生菌可以杀死超过 80% 痘痘细菌——外用益生菌也开始受到关注。" },
      { text: "不同菌株有不同的功能——Lactobacillus 和 Bifidobacterium 是研究最充分的两大类。" },
      { heading: "🦠 重点整理", text: "✅ 选择含有研究充分菌株的产品\n✅ 搭配膳食纤维效果更好\n❌ 不是所有益生菌都一样——菌株特异性很重要\n❌ 不要和热饮一起服用——高温会杀死活性菌" },
      { heading: "药师小贴士 💊", text: "💊 选购产品时，看成分比看广告更重要。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 NUCA® RevoBiotic——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-099",
    title: "这个护肤顺序问题，太多人忽略了",
    kicker: "Kris notes",
    category: "Supplement",
    date: "06 Sep 2025",
    readTime: "3 min",
    excerpt: "护肤顺序其实很简单——但很多人搞复杂了。你不需要十几步才能拥有好皮肤。",
    cover: "/products/fortress-plus-1.png",
    accent: "#a62f4f",
    body: [
      { text: "护肤顺序其实很简单——但很多人搞复杂了。你不需要十几步才能拥有好皮肤。" },
      { text: "先来看看研究怎么说。" },
      { text: "多余的产品反而可能增加刺激风险——不是越多越好。" },
      { text: "质地从薄到厚、从水基到油基——这是为了让每一步都能被皮肤吸收。" },
      { text: "正确顺序：清洁 → 精华 → 面霜 → 防晒（白天）。核心只需要这 4 步。" },
      { heading: "📋 重点整理", text: "✅ 清洁 → 精华 → 面霜 → 防晒——4 步足够\n✅ 新产品一个一个加入——不要同时引入太多\n✅ 晚上可以省略防晒，加入 A 醇或酸类\n❌ 不要一次叠加太多活性成分——会打架\n❌ 不要过度清洁——会破坏屏障" },
      { heading: "药师小贴士 💊", text: "💊 基础营养和良好生活习惯永远是第一位的。" },
      { text: "团购进行中 —— 见留言区 🛒" },
      { heading: "你可能也需要", text: "👉 Fortress+ Serum——了解更多见留言区" },
    ],
  },
  {
    slug: "pool-100",
    title: "为什么你的儿童护肤一直没效？",
    kicker: "Supplement truths",
    category: "Ingredient",
    date: "27 Jul 2025",
    readTime: "3 min",
    excerpt: "孩子的皮肤比成人薄——护肤品的选择原则就是：温和、简单。不需要大人的那些「进阶」产品。",
    cover: "/products/epsilon-cream-1.png",
    accent: "#2fa66b",
    body: [
      { text: "孩子的皮肤比成人薄——护肤品的选择原则就是：温和、简单。不需要大人的那些「进阶」产品。" },
      { text: "怎么说呢？" },
      { text: "日常只需要：温和清洁 + 基础保湿 + 防晒（6 个月以上）。" },
      { text: "儿童皮肤屏障功能还不完善——过度清洁反而会伤害皮肤。" },
      { text: "物理防晒（氧化锌）对儿童来说更安全——不会被皮肤吸收。" },
      { heading: "👶 重点整理", text: "✅ 温和清洁 + 基础保湿 + 防晒\n✅ 物理防晒对儿童更安全\n✅ 选择专门为儿童设计的产品\n❌ 不要用成人产品给孩子——浓度和成分不适合\n❌ 不要给孩子用美白、抗老产品——没必要" },
      { heading: "药师小贴士 💊", text: "💊 每个人的体质不同，适合别人的不一定适合你。" },
      { text: "关注Skinpiens，和Kris一起科学护肤。" },
      { heading: "你可能也需要", text: "👉 Epsilon Ultra Soothing Cream——了解更多见留言区" },
    ],
  },
];