import type { Product } from "@/lib/types";

export const FREE_SHIPPING_THRESHOLD = 150;

export const PRODUCTS: Product[] = [
  {
    id: "fortress-plus",
    slug: "fortress-plus-brightening-serum",
    name: "Fortress+ Brightening Serum with Illumys®",
    line: "Fortress+",
    tagline: "A tri-functional serum that brightens, soothes and reduces breakouts.",
    category: "Skin",
    price: 128,
    rating: 4.9,
    reviews: 1240,
    format: "30 ml",
    ingredients: [
      "Illumys® (Ginger Root)",
      "L. plantarum Postbiotic",
      "Tranexamic Acid",
      "Niacinamide",
      "Ceramides",
    ],
    badges: ["Hero", "Sensitive-safe", "Microbiome-balancing"],
    concerns: ["Brightening", "Sensitive", "Barrier Repair"],
    skinTypes: ["Sensitive", "Normal", "Combination", "Oily"],
    description:
      "A tri-functional serum that visibly brightens skin tone, soothes irritation, and helps reduce breakouts. Supercharged with Illumys®, this formula features a 10% brightening active blend of Illumys® (ginger root extract), L. plantarum postbiotic, Tranexamic acid, Niacinamide and Ceramides to promote a clearer, more radiant-looking complexion while reducing breakouts via skin microbiome balancing. Suitable for all skin types, including sensitive skin and those concerned with hyperpigmentation and acne marks.",
    hero: true,
    image: "/products/fortress-plus-1.png",
    gallery: [
      "/products/fortress-plus-1.png",
      "/products/fortress-plus-2.png",
      "/products/fortress-plus-3.png",
      "/products/fortress-plus-4.png",
      "/products/fortress-plus-5.png",
    ],
    art: { from: "#f7e8d8", to: "#e2b98f", accent: "#a65a2f", label: "F" },
  },
  {
    id: "epsilon-cream",
    slug: "epsilon-ultra-soothing-cream",
    name: "Epsilon Ultra Soothing Cream",
    line: "Epsilon Eczema",
    tagline: "Rapid itch relief in 30 minutes. Deep repair. All-day comfort.",
    category: "Eczema Range",
    price: 90,
    rating: 4.8,
    reviews: 986,
    format: "100 ml",
    ingredients: [
      "SymCalmin® (Oat Extract)",
      "Derma-Clera™",
      "Lassica K014® Postbiotic",
      "Panthenol",
    ],
    badges: ["Eczema-friendly", "30-min itch relief", "Dermatologist-tested"],
    concerns: ["Redness / Eczema", "Barrier Repair", "Dehydration"],
    skinTypes: ["Sensitive", "Dry"],
    description:
      "A deep-repairing, lightweight cream for face and body that provides rapid itch relief, tightens the skin barrier, and accelerates the recovery of compromised skin. Fortified with a deep-repair complex, this formula features a potent blend of SymCalmin® (Oat Extract), Derma-Clera™, Lassica K014® Postbiotic and Panthenol to deliver rapid itch relief in just 30 minutes while tightening skin gap junctions and inhibiting S. aureus to prevent future flare-ups.",
    hero: true,
    image: "/products/epsilon-cream-1.png",
    gallery: ["/products/epsilon-cream-1.png"],
    art: { from: "#dbeaf0", to: "#a8c9d6", accent: "#2f6a7d", label: "ε" },
  },
  {
    id: "epsilon-mist",
    slug: "epsilon-ultra-soothing-mist",
    name: "Epsilon Ultra Soothing Mist",
    line: "Epsilon Eczema",
    tagline: "Instant relief. Microbiome repair. Lasting comfort.",
    category: "Eczema Range",
    price: 60,
    rating: 4.7,
    reviews: 521,
    format: "150 ml",
    ingredients: [
      "Lassica K014® Postbiotic",
      "Colloidal Silver",
      "Menthol",
      "Menthyl Lactate",
    ],
    badges: ["Instant relief", "For body", "Flare-up calming"],
    concerns: ["Redness / Eczema", "Sensitive", "Dehydration"],
    skinTypes: ["Sensitive", "Dry"],
    description:
      "A fast-acting, ultra-soothing mist for body that instantly calms eczema flare-ups, reduces redness, and provides immediate relief from itching and discomfort. Formulated with a targeted antimicrobial complex, this formula features a potent blend of Lassica K014® Postbiotic, Colloidal Silver and Menthol + Menthyl Lactate to inhibit S. aureus (the primary bacteria causing flare-ups) while delivering a dual-action cooling relief. For body — avoid the eye area.",
    hero: false,
    image: "/products/epsilon-mist-1.png",
    gallery: ["/products/epsilon-mist-1.png"],
    art: { from: "#e3f1f5", to: "#b7d9e4", accent: "#3c7c94", label: "ε" },
  },
  {
    id: "epsilon-cleanser",
    slug: "epsilon-barrier-restoring-ceramide-cleanser",
    name: "Epsilon Barrier Restoring Ceramide Cleanser",
    line: "Epsilon Eczema",
    tagline: "A non-foaming, creamy cleanser that strengthens the barrier.",
    category: "Eczema Range",
    price: 50,
    rating: 4.6,
    reviews: 743,
    format: "200 ml",
    ingredients: ["Ceramides", "Lassica K014® Postbiotic", "Glycerin"],
    badges: ["Non-foaming", "Barrier repair", "Microbiome-safe"],
    concerns: ["Barrier Repair", "Sensitive", "Dehydration"],
    skinTypes: ["Sensitive", "Dry", "Combination"],
    description:
      "A non-foaming, creamy cleanser for face and body that strengthens the skin barrier, replenishes essential moisture, and gently removes impurities. This formula features a barrier-restoring blend of Ceramides and Lassica K014® Postbiotic to promote a healthy, hydrated skin surface while supporting a balanced skin microbiome. Suitable for all skin types, especially dry, sensitive and eczema-prone skin looking for a deeply moisturising yet soothing cleanse.",
    hero: false,
    image: "/products/epsilon-cleanser-1.png",
    gallery: ["/products/epsilon-cleanser-1.png"],
    art: { from: "#eef5f4", to: "#c9ddd8", accent: "#3f7a6d", label: "ε" },
  },
  {
    id: "nuca-revogard",
    slug: "nuca-revogard",
    name: "NUCA® RevoGard",
    line: "NUCA® Inner-Barrier",
    tagline: "Nutritional formula for digestive health and gut resilience.",
    category: "Supplement",
    price: 138,
    rating: 4.8,
    reviews: 312,
    format: "30 sachets",
    ingredients: ["Vitamin B12", "Vitamin C", "Calcium", "Iron", "Magnesium"],
    badges: ["Digestive health", "Pharmacist-formulated", "Clinically proven"],
    concerns: ["Barrier Repair", "Dehydration", "Aging"],
    skinTypes: ["All skin types"],
    description:
      "A nutritional formula for digestive health. Suitable for people with gastrointestinal symptoms. Take 1–2 sachets a day, mix with 150 ml lukewarm water, stir well and consume. Source of Vitamin B12, Vitamin C, Calcium, Iron and Magnesium. Clinically proven natural ingredients for digestive symptom and digestive health, formulated by pharmacists and nutritionists.",
    hero: false,
    image: "/products/nuca-revogard-1.jpg",
    gallery: [
      "/products/nuca-revogard-1.jpg",
      "/products/nuca-revogard-2.jpg",
      "/products/nuca-revogard-3.jpg",
    ],
    art: { from: "#f3e8d8", to: "#d9bfa0", accent: "#8a6a4a", label: "R" },
  },
  {
    id: "nuca-revobiotic",
    slug: "nuca-revobiotic",
    name: "NUCA® RevoBiotic",
    line: "NUCA® Inner-Barrier",
    tagline: "5-in-1 gut health: prebiotic + probiotic + postbiotic + enzymes + superfoods.",
    category: "Supplement",
    price: 128,
    rating: 4.7,
    reviews: 208,
    format: "30 sachets",
    ingredients: ["Prebiotics", "Probiotics", "Postbiotics", "Digestive Enzymes", "Fermented Superfoods"],
    badges: ["5-in-1 synergy", "No fillers", "Gut-skin axis"],
    concerns: ["Barrier Repair", "Brightening", "Aging"],
    skinTypes: ["All skin types"],
    description:
      "NUCA® RevoBiotic is a scientifically formulated 5-in-1 gut health solution that targets digestion, microbiome balance, and long-term gut resilience in one comprehensive formula. Combining Prebiotic + Probiotics + Postbiotic + Digestive Enzymes + Fermented Superfoods for complete gut nourishment. Every ingredient plays a clinically studied role — no fillers, only goodness.",
    hero: false,
    image: "/products/nuca-revobiotic-1.jpg",
    gallery: ["/products/nuca-revobiotic-1.jpg", "/products/nuca-revobiotic-2.jpg"],
    art: { from: "#ece6ef", to: "#c7bcd6", accent: "#6a5a8a", label: "B" },
  },
  {
    id: "epsilon-bundle",
    slug: "epsilon-bundle",
    name: "Epsilon Bundle",
    line: "Epsilon Eczema",
    tagline: "The complete barrier ritual — cleanser, cream and mist.",
    category: "Eczema Range",
    price: 160,
    compareAt: 192,
    rating: 4.9,
    reviews: 431,
    format: "3-piece ritual",
    ingredients: ["Ceramide Cleanser", "Soothing Cream", "Soothing Mist"],
    badges: ["Bundle", "Save RM 32", "Full ritual"],
    concerns: ["Redness / Eczema", "Barrier Repair", "Sensitive"],
    skinTypes: ["Sensitive", "Dry"],
    description:
      "The complete Epsilon barrier ritual in one box: the Barrier Restoring Ceramide Cleanser, Ultra Soothing Cream and Ultra Soothing Mist. Cleanse, repair and calm — everything eczema-prone skin needs, delivered as a full 3-step system. Save RM 32 versus buying separately.",
    hero: false,
    image: "/products/epsilon-bundle-1.png",
    gallery: ["/products/epsilon-bundle-1.png"],
    art: { from: "#dbeaf0", to: "#9fbfca", accent: "#2f6a7d", label: "ε" },
  },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function formatMYR(value: number): string {
  return `RM ${value.toFixed(2)}`;
}
